### ISSUE TITLE
1.3.1 Unplayable due to crashing

### ISSUE THREAD

**Issue by SirApetus** [FTBTeam/FTB-Presents-Direwolf20-1.16#100]
My boyfriend and I keep crashing 

Modpack Version: 1.3.1

Issue: Crashing to desktop every few minutes. It is a brand new 1.3.1 server from Bisecthosting, 7gb of ram, and we each are allocating 6gb of ram to Minecraft.

Link to Log or Crash File Paste: https://pastebin.com/skkMbNm8, https://pastebin.com/vvk66WWK

Is it Repeatable?: Keeps happening, not sure how to cause it though

Mod/s Affected:

Known Fix:

Edited to add new paste bin(https://pastebin.com/vvk66WWK)

**Comment by bubbafett5611** [comment]
I'm not great at reading the logs, however it looks like the issue might be getting caused by a Create Minecart Controller.

`java.lang.NullPointerException: Unexpected error
	at com.simibubi.create.content.contraptions.components.structureMovement.train.capability.CapabilityMinecartController.tick`
	
Again, I'm not the best at reading logs so I could be wrong.

**Comment by Dutchs** [comment]
Try removing Optifine, or update it to OptiFine HD U G6 pre12.
Forge got updated in 1.3.0 and it looks like optifine broke because of it.

**Comment by drrk** [comment]
I've been having the same issue, and followed the bug on the Create repo: https://github.com/Creators-of-Create/Create/issues/669  which has just been fixed, and is released on Curseforge, hopefully the pack can be updated :)
