### ISSUE TITLE
Autoconstruction in Environmental Tech does not work since update

### ISSUE THREAD

**Issue by Terminator81** [FTBTeam/FTB-Presents-Direwolf20-1.16#102]
* **Modpack Version**: 1.3.1

* **Issue**: since update 1.3.1 the autoconstruction of the void miner does not work anymore

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: Environmental Tech

**Comment by luchokoldo** [comment]
works fine, the void miner now has a button in the interface

**Comment by Terminator81** [comment]
so no more shift-right-click

**Comment by Terminator81** [comment]
works fine
