### ISSUE TITLE
constant game crash when loading worlds

### ISSUE THREAD

**Issue by briggsmech** [FTBTeam/FTB-Presents-Direwolf20-1.16#103]
* **Modpack Version**:all
* **Issue**: i have been playing 1.2 Then updated to 1.3 after that all worlds crash on loading

* **Link to Log or Crash File Paste**:https://paste.feed-the-beast.com/view/97ba6967
* **Is it Repeatable?**: yes
* **Mod/s Affected**: looks like emojiful is the source of the problem
* **Known Fix**:

**Comment by CodingJawa** [comment]
can confirm, updated from 1.3.0 to 1.3.1 now my save is corrupted. cannot load. I tried downgrading back to 1.3.0 but safefile is corrupted now.

**Comment by CLASIX** [comment]
Confirming as well. Updated to 1.3.1 and I crash on world load. Here is my crash log as well https://paste.feed-the-beast.com/view/5b3028b6

**Comment by CLASIX** [comment]
> can confirm, updated from 1.3.0 to 1.3.1 now my save is corrupted. cannot load. I tried downgrading back to 1.3.0 but safefile is corrupted now.



> can confirm, updated from 1.3.0 to 1.3.1 now my save is corrupted. cannot load. I tried downgrading back to 1.3.0 but safefile is corrupted now.

Downgrade the pack. Go the DW's main page on the launcher. Hit open folder on the right hand side. go to backups. go into the very bottom zipped folder and copy your world folder. Throw that in the saves folder in the ftb directory and boom. your back in business. albeit a few hours behind. but hey, that a heck of a lot better than a corrupted world.

**Comment by Dutchs** [comment]
Try removing Optifine, or update it to OptiFine HD U G6 pre12.
Forge got updated in 1.3.0 and it looks like optifine broke because of it.

**Comment by CodingJawa** [comment]
sadly did not work. nuked my savegame completely. I am stuck at the 100% loading screen. does not show up in logs, so yey

**Comment by DoomieWoomie** [comment]
I am having the same problem. Updated to 1.3.1 and save got stuck at 100%. Tried downgrading and still doesn't work. I guess I'll have to use a backup or start over.  :/

**Comment by Sunekaer** [comment]
@briggsmech could you also give me your latest.log?
