### ISSUE TITLE
1.31 Portal to Ratlantis still takes me to 0,0,0 in overworld

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Presents-Direwolf20-1.16#104]
* **Modpack Version**: 1.3.1

* **Issue**: Portal to Ratlantis still takes me to 0,0,0 in overworld
* 
* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Seems so try to enter 15 or more time even after rebuilding portal. 

* **Mod/s Affected**: Rats

* **Known Fix**: 

I removed the folder for the dim and it seems to pause says building then back to overworld.  

Dim is made can teleport to it using
/execute in rats:ratlantis run teleport @s 1 112 0
portal in ratlantis does not work to return to overworld, Assuming a mod bug maybe

**Comment by Sunekaer** [comment]
Could i get you to try and make a new save and see if it also happens in that one?

**Comment by robertm1771** [comment]
Yes even in a clean new game seems dim is made but teleported to 0 90 0  to correct the 0 0 0 in my first post

**Comment by Sunekaer** [comment]
Okay in my dev instance it takes me to Ratlantis, but I also use a newer version so let's see if it's fixed in next update

**Comment by robertm1771** [comment]
same with 1.4.1 as with 1.3.1 when I get a chance will make new instance and see what happens.  This instance started with 1.0 I cant help but wonder if its a dim ID problem. If a command runs to teleport me to dim that doesn't exist I assume is the results am seeing. But am unsure.

**Comment by robertm1771** [comment]
New Instance seems to work going to ratlantis, coming back to overworld take you to 0 90 0 not sure that is as expected but expect its the mod its self.

**Comment by robertm1771** [comment]
Seem to be something in my instance unsure if its fixable but I have my workaround I can use. 

Thanks
