### ISSUE TITLE
AE2 Meteor Generation Deadlock

### ISSUE THREAD

**Issue by NachtRaben** [FTBTeam/FTB-Presents-Direwolf20-1.16#105]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4891

* **Modpack Version**: 
1.3.1
* **Issue**: 
Random AE2 crater deadlocks. These are craters that will persistently cause the chunk generation threads to deadlock.
* **Link to Log or Crash File Paste**: 
No logs or crashes, just infinite deadlock
* **Is it Repeatable?**: 
Absolutely, details listed in the associated open issue with AE2
* **Mod/s Affected**: 
Applied Energistics 2
* **Known Fix**: 
None

**Comment by Sunekaer** [comment]
duplicate #84
