### ISSUE TITLE
Optifine crashes 1.31

### ISSUE THREAD

**Issue by Hypocertise** [FTBTeam/FTB-Presents-Direwolf20-1.16#106]
I was crashing after update to 1.3.1 Exit Code 0 So after reinstalling minecraft and direwolf20 1.16 I removed the one mod I added Optifine and the issue resolved itself I worked prior to 1.3.1 update Sorry in my hurry to fix the issue I didnt save a log but as it resolved after removing that mod and I saw other places where that was a fix for others I'm guessing issue somewhere there between them thanks

**Comment by FiveEYZ** [comment]
I know adding optifine isnt supported by the pack, updated to `preview_OptiFine_1.16.4_HD_U_G6_pre7.jar` in 1.3.0 and is still working just fine in 1.3.1

**Comment by Sunekaer** [comment]
We do not support OptiFine
