### ISSUE TITLE
End doesn't exist in my world? 

### ISSUE THREAD

**Issue by imfeared** [FTBTeam/FTB-Presents-Direwolf20-1.16#107]
* **Modpack Version**: 1.3/1.3.1

* **Issue**: 
The end doesn't exist in my world. I tried entering the end portal once updated and I just fell right through it. Using the command "/execute in (dimension) run teleport", I don't even see "the end" on the list of dimensions. I tried downgrading the version did nothing. 

* **Link to Log or Crash File Paste**: 
* https://paste.feed-the-beast.com/view/420b4681 (Latest log)

* **Is it Repeatable?**: I have Zero knowledge on why this is happening.
* Edit: I could send my world, which I don't know how to do.

* **Mod/s Affected**: Optifine caused me to crash when I went to 1.3/1.3.1

* **Known Fix**: Don't know.

**Comment by M4RC0Sx** [comment]
It happened to me to. I think it was while creating the Void Dimension portal.

**Comment by rahangar** [comment]
I'm seeing the same issue.  I fall right through the portal.

**Comment by imfeared** [comment]
Found a fix.... 

Use NBTExplorer to paste the dimension "minecraft:the_end" from another save.
