### ISSUE TITLE
Create mixer missing shapeless crafting

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Presents-Direwolf20-1.16#108]
* **Modpack Version**: 1.3.1

* **Issue**: Automated shapeless crafting for the create mixer shown in this spotlight video isn't in game, and the recipes don't craft (ignoring that it's missing from JEI): https://youtu.be/zQnPQeeHHLM?t=1035

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yep

* **Mod/s Affected**: Create

* **Known Fix**: Unknown. Server config shows shapeless crafting in the mixer is enabled.

* **Other**:  Just tested on a 1.2.0 instance in single player, seems to be missing there too.

**Comment by Sunekaer** [comment]
https://github.com/malte0811/RecipeBuffers/issues/3

**Comment by Sunekaer** [comment]
fixed in  1.4.0 and up
