### ISSUE TITLE
Tooltips are ridiculously large and should be off by default

### ISSUE THREAD

**Issue by GrumpyChunks** [FTBTeam/FTB-Presents-Direwolf20-1.16#111]
* **Modpack Version**: 1.3.1

* **Issue**: Tooltips are way too large, and can't be switched off.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Yes, occurs all the time

* **Mod/s Affected**: n/a

* **Known Fix**: Edit options.txt to change the following value to false: `advancedItemTooltips:false`

* **Operating System/Software**: Mac OS / FTP App

The size of the tooltips is ridiculous in many instances. I've seen some that fill the screen from top to bottom. [This](https://imgur.com/a/skE4IfA) is an example of the tooltip on a simple iron ingot, it shows how annoying this is when you're trying to manage your inventory and the tooltip completely covers the inventory. It's even worse when you hold down the shift key whilst hovering, as even more information appears in the tool tip.

When Minetogether was in the pack, you would frequently see people asking how to disable it, I've also seen a number of posts in the FTB discord asking how to disable it, and a few other people (I assume Mac users) reporting that F3+H doesn't work.

Surely this extended debug information should be off by default?

**Comment by quietust** [comment]
I believe if you press F3+H it'll hide all of the tag information, though it'll also hide things like tool durability.

**Comment by GrumpyChunks** [comment]
As stated in my report, F3+H doesn't work. Possibly because I'm on a Mac?

**Comment by GrumpyChunks** [comment]
Found a workaround, edited the report to include it.

**Comment by Sunekaer** [comment]
I think you have to press Fn + F3 + H on macs

**Comment by GrumpyChunks** [comment]
@Sunekaer Yes this is correct with a default MacOS install, unless of course you change the way the function keys work in MacOS. When I stated 'F3+H' in the report, I perhaps should have made this clear given this is a Mac, but it's implied that the Fn key is being pressed on a Mac.

For info, F3 (or Fn + F3) does bring up the normal debug overlay, but F3+H (or Fn+F3+H) doesn't work.

Regardless of the problem of F3+H working or not working, that isn't really the issue here. The issue really is why are these advanced tooltips enabled by default in the pack? If they weren't obnoxiously huge, it wouldn't be so bad, but they really hamper inventory management, and in my opinion don't contain any useful info. It's a simple fix that will make a big improvement in usability of the pack. If a player really wants or needs that screenful of redundant low level detail frustrating their inventory management, they will already know how to enable it.

**Comment by Sunekaer** [comment]
Well it doesnt look that big on my screen, it depends on the res of your screen and scale set in the settings.
But will disable it the default conf
