### ISSUE TITLE
Servercrash after trying to reset JAMD

### ISSUE THREAD

**Issue by Terminator81** [FTBTeam/FTB-Presents-Direwolf20-1.16#112]
* **Modpack Version**: 1.3.1
* **Issue**:  i tried to reset the mining dimension by moving the folder out of the server, but it crashes. Also if i take a backup it crashes too.
* 
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4d33ba6c

* **Is it Repeatable?**: yes

**Comment by djanse** [comment]
I've removed the mining dimension several times without issue. Is your server still online when you delete the folder?
What we do is delete the folder inside jamd called 'mining' when the server is offline.

**Comment by Terminator81** [comment]
if have fixed to by deactivating the server watchguard
