### ISSUE TITLE
Lightwells not working for Fake Players in claimed chunks on SMP

### ISSUE THREAD

**Issue by LezChap** [FTBTeam/FTB-Presents-Direwolf20-1.16#114]
* **Modpack Version**: 1.3.1

* **Issue**: When using a Fake Player (Item User from Cyclic, Modular Router, etc) to place aquamarine or other items in a Lightwell, if the chunk is claimed, the Fake Player will not work as expected (nothing gets placed in Lightwell).  Unclaimed chunks it still works.  This only seems to happen in SMP (servers), and works fine in claimed chunks in Single Player.  Friending the Fake Player via FTB Chunks (or associated GUI) does not seem to solve the problem.  Ref: https://github.com/FTBTeam/FTB-Chunks/issues/86

  Adding the issue here so it's tracked for when it's fixed for the pack.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: FTB Chunks (believe this is the mod causing the issue), Astral Sorcery, Cyclic, and Modular Routers

* **Known Fix**: none yet

**Comment by LatvianModder** [comment]
You can add the fake player as ally in your FTB Chunks menu, from inventory top-left

**Comment by LezChap** [comment]
> You can add the fake player as ally in your FTB Chunks menu, from inventory top-left

I swear I tried that last time and it didn't work.  Just tested again, and it seems to get the Router working...so I must have done it wrong last time.
