### ISSUE TITLE
Rat's mod Trash infinite trash bug

### ISSUE THREAD

**Issue by DA3monking** [FTBTeam/FTB-Presents-Direwolf20-1.16#115]
when piping into the trash bin, if using multiple output points from a chest, give disproportional amounts of trash. 
example, refined pipes advanced pipes with ultimate extractors. 5 on chest and one connection to the bin, will not use the items in chest and give trash, so long as more than one item is inserted to the chest at one time, see picture for setup
![Screenshot (10)](https://user-images.githubusercontent.com/69975658/104504677-cd2fd080-55b0-11eb-9331-8762faf189fc.png)

**Comment by Sunekaer** [comment]
Already fixed in a newer version of the mod
