### ISSUE TITLE
Ores not generating 

### ISSUE THREAD

**Issue by nbargate** [FTBTeam/FTB-Presents-Direwolf20-1.16#117]
* **Modpack Version**:1.3.1 

* **Issue**: Ores not generating. Tried multiple "new worlds", and lots of the ores do not seem to be generating. This includes, but may not be limited to all mekanism ores, Powa ores, Thermal Expansion 

* **Link to Log or Crash File Paste**: Not crash log present. 
* **Is it Repeatable?**: Yes, all new saves have this issues for me. 

* **Mod/s Affected**: Mekanism, Powa, Thermal

**Comment by Sunekaer** [comment]
Did you add or change anything to the pack?
Logs?

**Comment by nbargate** [comment]
No, its as the pack comes. 

not 100% sure how to get a log if it hasn't crashed

**Comment by Sunekaer** [comment]
Thats weird.
In the logs folder latest.log

**Comment by nbargate** [comment]
Please see the linked paste bin 

**https://pastebin.com/0HgLBBHi**

**Comment by nbargate** [comment]
Upon closer inspection, by running a digital miner over 32 Chunks. They do seem to be spawning in my new world. 

I updated the pack to 1.4.1
