### ISSUE TITLE
Can't Play: Mods are not installed

### ISSUE THREAD

**Issue by Kratzwurst** [FTBTeam/FTB-Presents-Direwolf20-1.16#12]
# FTB-Presents-Direwolf20-1.16
Modpack Version: 1.0.0
Launcher: FTB APP (Windows 10)
Issue: 
I guess the APP cannot recognize the correct files, but there are in folder and right installed.
And this Pack are not listed on Curseforge/Overwolf

Link to Log or Crash File Paste:
17 Files Missing https://pastebin.com/LR5vtrXT

Is it Repeatable?:
First install: 17 Mods are not installed, but they are in Folder.
Second Installation: 8 Missing Mods.

Mod/s Affected:

Known Fix:

**Comment by Sunekaer** [comment]
Reinstall the pack and if that doesnt help please report it in discord in the #ftb-app channel or on https://github.com/FTBTeam/FTB-App so the app devs can look at the issue 
Thanks
