### ISSUE TITLE
Milk drained from milk bucket by Create:item_drain incompatible with other mods

### ISSUE THREAD

**Issue by VorpalLemur** [FTBTeam/FTB-Presents-Direwolf20-1.16#121]
* **Modpack Version**: 1.3.1

* **Issue**:   If you use the "item drain"  (Create) to drain milk from milk buckets, you can't then use that milk in the Fluid Encapsulator (Thermal) to make milk buckets.   Also if you put the milk into a tank (Mekanism) and try to hit the tank with a bucket, you'll void your bucket (and 1B of milk from the tank); no milk bucket is created.

I encountered this while trying to automate milk production/storage so I can autocraft with milkbuckets using Refined Storage. 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thermal Series, Create, Mekanism

* **Known Fix**:

**Comment by Sunekaer** [comment]
Okay so i changed it to give Industrial Foregoing Milk and that seem to fix all of this in my dev instance.
