### ISSUE TITLE
Recipe conficts with witch hats making glowstone/redstone/gunpowder

### ISSUE THREAD

**Issue by shinji257** [FTBTeam/FTB-Presents-Direwolf20-1.16#122]
* **Modpack Version**: 1.3.1

* **Issue**: Witch hats have the same pattern/recipe for making 6 of either glowstone, redstone, or gunpowder.

* **Link to Log or Crash File Paste**:
![image](https://user-images.githubusercontent.com/261005/104816318-5bda6280-57e8-11eb-90a8-07a097caaef5.png)
![image](https://user-images.githubusercontent.com/261005/104816320-5e3cbc80-57e8-11eb-999c-cd7c24a4380a.png)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Reliquary

* **Known Fix**: Recipe change or there may be a mod that allows to choose which recipe to use.

**Comment by Sunekaer** [comment]
https://github.com/P3pp3rF1y/Reliquary/issues/488

**Comment by Sunekaer** [comment]
ill add another recipe for these until the dev has fixed this.

**Comment by Snappiestjack** [comment]
This is still an issue in 1.5.1, which came out after Fixed in Dev tag so I'm assuming it's not fixed.

**Comment by Snappiestjack** [comment]
I updated KubeJS to use the 1st, 2nd and 4th crafting slots for redstone and that works. 

Appears the vanilla bug applies to diagonal recipes too.
