### ISSUE TITLE
Create Deployer isn't deploying 

### ISSUE THREAD

**Issue by dddkzxz** [FTBTeam/FTB-Presents-Direwolf20-1.16#123]
Modpack Version: 1.3.1

Issue:  Create Deployer isn't deploting, it accepts items " in hand" and in filter, its moving when supplied with SU. it makes the placing sound of items but there is nothing there. Tried to relog or exit completely, it didn't help.. 

Mod/s Affected: Create

**Comment by MacChuck** [comment]
If you are trying to deploy in a protected area by FTB Chunks or Minecolonies, you need to add the deployer to your ally's or colony list.

**Comment by dddkzxz** [comment]
thank you, how can I do it?
