### ISSUE TITLE
Recipes missing from JEI

### ISSUE THREAD

**Issue by minsterxev** [FTBTeam/FTB-Presents-Direwolf20-1.16#126]
* **Modpack Version**: 1.3.1

* **Issue**: Numerous recipes are not listed in JEI.  Two that come to mind are "Firework Star" and "Firework"
* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Mana and Artifice
* **Known Fix**: Google the recipe needed.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed
