### ISSUE TITLE
Error in data packs

### ISSUE THREAD

**Issue by hyrpxninja** [FTBTeam/FTB-Presents-Direwolf20-1.16#127]
* **Modpack Version**: 

* **Issue**:
*i am playing the new FTB Direwolf 1.16 modpack, i have added a few mods of my own to the pack. I loaded the world yesterday perfetcly fine, but today when i go to load the world it gives me this error - "Errors in currently selected datapacks prevented world … ... with vanilla datapack (“safe mode”) or go back to title screen and fix it manually." Safe mode doesn't do anything

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Once you have edited the pack we don't offer support and it could cause many issues that we don't know about and we have no clue what could be causing your issues
