### ISSUE TITLE
Electric Pump (mekanism) unable to pick up pneumaticraft:crude_oil from world

### ISSUE THREAD

**Issue by VorpalLemur** [FTBTeam/FTB-Presents-Direwolf20-1.16#129]
* **Modpack Version**: 1.4.1

* **Issue**: Placing an Electric Pump (mekanism) directly over a pool of pnemuaticraft:crude_oil source blocks in the world does not register as a valid fluid to the Electric Pump.  Pump reports "no fluid".   Works as expected with other liquids.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Mekanism, Pneumaticraft

* **Known Fix**: Gas Lift (pneumaticraft) can pick up the blocks fine.

**Comment by VorpalLemur** [comment]
Fluid Pump (immersive engineering) also has no problems picking up crude_oil

**Comment by MacChuck** [comment]
It is possible this is intentional by the Pneumatriccraft dev. If you've jumped into those pools, they don't act like a fluid normally would.

**Comment by VorpalLemur** [comment]
> It is possible this is intentional by the Pneumatriccraft dev. If you've jumped into those pools, they don't act like a fluid normally would.

According to the pneumaticraft in-game manual, the recommended method to pump those pools is to use the pneumaticraft Gas Lift, but they note that other fluid pumping machines from other mods should work to so I doubt the intended Mekanism to be specifically left out (since, as noted, Immersive Engineering's pump works fine)

**Comment by Sunekaer** [comment]
https://github.com/mekanism/Mekanism/issues/6907

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
