### ISSUE TITLE
Can't craft Blood Magic Sentient Tools

### ISSUE THREAD

**Issue by DXHHH101** [FTBTeam/FTB-Presents-Direwolf20-1.16#13]
* **Modpack Version**: 1.0

* **Issue**: The sentient tools in Blood Magic are uncraftable. There's no recipe in JEI, and the "correct" recipe doesn't work anyways.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Blood Magic

**Comment by Sunekaer** [comment]
https://github.com/WayofTime/BloodMagic/issues/1727

**Comment by VT-14** [comment]
https://github.com/KubeJS-Mods/KubeJS-Blood-Magic/issues/1
