### ISSUE TITLE
Create Schematic Cannon broke on placing Ender Tank

### ISSUE THREAD

**Issue by 923penguin** [FTBTeam/FTB-Presents-Direwolf20-1.16#130]
[crash-2021-01-17_14.46.45-server.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5826690/crash-2021-01-17_14.46.45-server.txt)

Title explains it. Was using a Schematic Cannon to place blocks in the nether for an infinite lava setup, it broke when trying to place the ender tank. Haven't tried loading the world again yet, will update if it's corrupted or anything.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by 923penguin** [comment]
Modpack Version: 1.4.1
Issue: Game crashes when using a schematic cannon to place an ender tank
Link: https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5826690/crash-2021-01-17_14.46.45-server.txt
Repeatable: Probably, I haven't tried it again since it crashed my world the first time
Mods affected: Create, Ender Storage
Known Fix: After some experimenting, I was able to save my world by removing ender storage, loading the world, and adding it back in. Had to go back and replace all my ender storage, but it worked.

**Comment by Sunekaer** [comment]
https://github.com/TheCBProject/EnderStorage/issues/149

**Comment by covers1624** [comment]
This has been fixed in EnderStorage, refer to the linked ES issue for build numbers.
