### ISSUE TITLE
Create Copper ore missing forge tag

### ISSUE THREAD

**Issue by Sites94** [FTBTeam/FTB-Presents-Direwolf20-1.16#132]
* **Modpack Version**: 1.4.1

* **Issue**: Copper Ore from Create is being found in the world (somehow?) and does not have the forge:ores/copper tag on it so it cannot be used in any way

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Create

* **Known Fix**: There is no fix as not even the oredictionafier from Mekanism will merge this as its only listed as forge:ores
![image](https://user-images.githubusercontent.com/7807439/104858708-7a904480-5921-11eb-81d1-56a7a8b6d842.png)

**Comment by Sunekaer** [comment]
Which dim did you find create copper in? 
As create copper is disabled this is very confusing for me

**Comment by Sites94** [comment]
Found in the overworld which is DIM 0, I've been using the same world since modpack release, so maybe that might be the issue, I have no problems deleting the items and replacing them, I just wanted to raise the issue because I thought it might be important, but if worldgen for this ore is disabled then please mark this as resolved 👍

**Comment by grekiki** [comment]
Same issue here on dw20 pack
