### ISSUE TITLE
Several Plates missing recipes

### ISSUE THREAD

**Issue by SonicSpeedster16** [FTBTeam/FTB-Presents-Direwolf20-1.16#133]
* **Modpack Version**: 1.4.0

* **Issue**: Several types of plates are missing recipes

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal, Create, Immersive Engineering

* **Known Fix**: Add custom recipes/wait for mods to add recipes

Iron, Gold, and Copper Plates can all be crafted in a crafting table using the Immersive Engineering Hammer, in the IE Metal Press, Create's Automated Shapeless Crafting, Create's Pressing, or it the Multiservo Press. Several plates are missing some of these options:

Tin Plate - missing the Crafting Table and Create recipes
Lead Plate - missing the Create Pressing recipe
Silver Plate - missing the Create Pressing recipe
Nickel Plate - missing the Create Pressing recipe
Bronze Plate - missing the Crafting Table and Create recipes
Electrum Plate - missing the Create Pressing recipe
Invar Plate - missing the Crafting Table and Create recipes
Constantan Plate - missing the Create Pressing recipe
Signalum Plate - missing the Crafting Table, Metal Press and Create recipes
Lumium Plate - missing the Crafting Table, Metal Press and Create recipes
Enderium Plate - missing the Crafting Table, Metal Press and Create recipes

**Comment by Snappiestjack** [comment]
Was about to post regarding this. 

Hope this gets updated but in the mean time i've added the following to \kubejs\server_scripts\recipes\create

	event.recipes.create.pressing(['thermal:tin_plate'],'thermal:tin_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:lead_plate'],'thermal:lead_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:silver_plate'],'thermal:silver_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:nickel_plate'],'thermal:nickel_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:bronze_plate'],'thermal:bronze_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:electrum_plate'],'thermal:electrum_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:invar_plate'],'thermal:invar_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:constantan_plate'],'thermal:constantan_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:signalum_plate'],'thermal:signalum_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:lumium_plate'],'thermal:lumium_ingot').processingTime(60)
	event.recipes.create.pressing(['thermal:enderium_plate'],'thermal:enderium_ingot').processingTime(60)

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
