### ISSUE TITLE
some alternate stone not in mining dimension

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Presents-Direwolf20-1.16#135]
* **Modpack Version**: 1.4.0

* **Issue**: Mining dimension is missing diorite, gabbro, andesite, granite. It does have limestone, scoria, and extcaves stone.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: jamd, create, vanilla

**Comment by ehertlein** [comment]
I believe that is just how its configured by default. I was able to use this datapack on my local game to add those stone types back.
[jamdWithAlternateStone.zip](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5839473/jamdWithAlternateStone.zip)

**Comment by MacChuck** [comment]
> I believe that is just how its configured by default. I was able to use this datapack on my local game to add those stone types back.
> [jamdWithAlternateStone.zip](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5839473/jamdWithAlternateStone.zip)

I couldn't find any documentation on how to configure it, where did you find that out?

**Comment by ehertlein** [comment]
Noticed this on the curseforge page:

> Adds a simply mining dimension, simply craft The Mining Portal and then right-click and boom your in the mining dimension
> Mining dimension is editable with datapacks. see Github page for example datapack 

Then I went here: [https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/worldgen/biome/mining.json](https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/worldgen/biome/mining.json).

After that I looked up how to add features to the mining.json biome. I used this sight as a reference:
[https://misode.github.io/worldgen/biome/](https://misode.github.io/worldgen/biome/)

Hopefully that helps you customize the mining dimension how you would like.

**Comment by Sunekaer** [comment]
Its been fixed by the dev in the latest update of the mod no need to make datapacks, just wait for a pack update

**Comment by ehertlein** [comment]
Would you look at that. He updated it 2 days ago. Awesome. At least with the datapack I was able to have all the alternate stone since I started playing.
