### ISSUE TITLE
Delivery Hut upgrade to level 5, shulker box not recognized by the builder.

### ISSUE THREAD

**Issue by dddkzxz** [FTBTeam/FTB-Presents-Direwolf20-1.16#136]
* **Modpack Version**: 1.4.1
* **Issue**: When I'm trying to upgrade the delivery hut building(from minecolonies) the builder askes for a brown shulker box, When I'm giving it to him he doesn't recognize it. He still asks for a brown shulker box.
The resource scroll also shows 1 shulker box is missing.
* **Is it Repeatable?**: yes

* **Mod/s Affected**: Minecolonies

* **Known Fix**: if given 2 or 3 shulker box's he doesnt ask for more.

**Comment by Sunekaer** [comment]
@dddkzxz could i get you to report this on https://github.com/ldtteam/minecolonies/issues as you know more about this issue then I do and would be able to answer questions they have.
