### ISSUE TITLE
Different AE2 Cables don't connect to each other

### ISSUE THREAD

**Issue by ArcaneEternal** [FTBTeam/FTB-Presents-Direwolf20-1.16#137]
* **Modpack Version**: 1.4.1

* **Issue**: Placing dyed (Covered/Smart) (Dense/Glass) Cable next to any Cable type other than Fluix and they will not connect. E.g. White Dense Cable and Red Glass Cable do not connect. Not sure if this is the intended nature of these cables or if it is indeed a bug. My understanding was that only the different dyed versions of the same type (i.e. Red Glass and Blue Glass) shouldn't connect to each other.

![AE2 Cable Issue](https://user-images.githubusercontent.com/77667244/105017664-26f43700-5a98-11eb-96ea-105754a62061.png)

* **Is it Repeatable?**: Yes. Simply place down some ME cables and see what connects.

* **Mod/s Affected**: AE2 V8.2.0 Beta 2

**Comment by Dhvagra** [comment]
That's by design and has always been in AE2. Color X doesn't connect to color Y, only with an intermediate fluix cable.

**Comment by Sunekaer** [comment]
AS Dhvagra, thats by design

**Comment by ArcaneEternal** [comment]
Ok sweet :)
