### ISSUE TITLE
Create Zinc Ore missing Mekanism enrichment recipe

### ISSUE THREAD

**Issue by shubidubapp** [FTBTeam/FTB-Presents-Direwolf20-1.16#138]
* **Modpack Version**: 1.4.1

* **Issue**: Create Zinc Ore is missing a ore doubling recipe by Mekanism while it has a Zinc Ore -> 2x Crushed Zinc Ore recipe in Pulverizer (Thermal Series). It has a ore doubling recipe using thermal series but it doesn't have any for Mekanism.

* **Is it Repeatable?**: It is there nothing to reproduce...

* **Mod/s Affected**: Mekanism, Create

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
