### ISSUE TITLE
1.4.1 Server crash

### ISSUE THREAD

**Issue by Howsyomamanem** [FTBTeam/FTB-Presents-Direwolf20-1.16#140]
* **Modpack Version**: 1.4.1

* **Issue**: Server crashes on startup

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/fd582bde

* **Is it Repeatable?**: yes, 3 times so far.

* **Mod/s Affected**: the crash log implies its pneumaticcraft-repressurized-1.16.4-2.9.2-116.jar.  I haven't started using this mod in the world yet...  but honestly, it doesn't even get to the point of loading the world before the crash.

* **Known Fix**: downgraded to 1.3.1 version of pack.

**Comment by Sunekaer** [comment]
Seems like you havent updated forge with the server update

**Comment by freedg** [comment]
The start.bat/start.sh script has to be manually updated to launch the new forge version. 
Simply replace `forge-1.16.4-35.1.13.jar` with `forge-1.16.4-35.1.36.jar`.

**Comment by BScheller75** [comment]
I am having the same issue with flux networks. I deleated the file and redownloaded the most current version from forge but my world still won't load.
