### ISSUE TITLE
Server Not Responsive

### ISSUE THREAD

**Issue by BScheller75** [FTBTeam/FTB-Presents-Direwolf20-1.16#142]
* **Modpack Version**: <1.16-1.4.1>

* **Issue**: When I try to load up the world I've been playing on the server becomes nonresponsive after reading world data. This world was working a few hours before but now will not load.

* **Link to Log or Crash File Paste**: <https://paste.feed-the-beast.com/view/6d773117>

* **Is it Repeatable?**: Yes I have tried loading this world many times

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by freedg** [comment]
Could you upload or paste the contents of `culinaryconstruct-server.toml`? It should be located in the folder `serverconfig` in the world folder for your sever.

**Comment by BScheller75** [comment]
I tried opening that file in notepad and it was empty. Sorry I do not know how else I would upload the file

**Comment by BScheller75** [comment]
I was able to create a new world that loaded successsfully. I also noticed that multiple config files were now blank in my original world, but they were not blank in the save folder for this new world. Would it work to replace the config files in my original world with the config files from my new save?

**Comment by freedg** [comment]
Yes, that should work. Alternately, I believe deleting the config files and re-installing the server would also fix the problem.
