### ISSUE TITLE
ores

### ISSUE THREAD

**Issue by Apwalchan** [FTBTeam/FTB-Presents-Direwolf20-1.16#144]
none of the basic Minecraft ores drop anything when picked, coal drops exp but no coal.. the added mod ores drop their stuff but nothing for iron or coal so far

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by Apwalchan** [comment]
there was no template, it was blank, hence why I didn't do it correctly

**Comment by Apwalchan** [comment]
but regardless completely restarting the world fixed the issue
