### ISSUE TITLE
Rock Crystals 'rarity' / Extended Caves / Mining gadget

### ISSUE THREAD

**Issue by DePhoegon** [FTBTeam/FTB-Presents-Direwolf20-1.16#145]
* **Modpack Version**: Every Version

* **Issue**: Extended caves,  more lavastone then stone @ bedrock, enough lava pools & rivers in the overworld to trick me into thinking the nether invaded, rock Crystals so rare it's insane (requiring void miners to legitimately obtain them)
-- .... A suspiciously seriously abnormally large number of Natural Scoria ( near bedrock, 2nd only to lavarock patches )
-- Mining Gadget
== Doesn't Count towards stats
== Doesn't respect mining fatigue (as much of a pain as that would be)
== Is able to remove tetra building elements [though honestly I kinda am over tetra progression & in the way buildings... soooo  This one isn't so bad]

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: It's Constent

* **Mod/s Affected**: Astral / Extended Caves / Create

* **Known Fix**: Cheating in Astral Ore (rock crystal), & using the mining gadget w/ freezing, to deal with the crazy amount of lava.

**Comment by Sunekaer** [comment]
Rock crystal issue was solved, but if your world is from before that fix you'll have to explore new chunks to fine the ores.
