### ISSUE TITLE
Surface Crude Oil Interaction

### ISSUE THREAD

**Issue by crispyv** [FTBTeam/FTB-Presents-Direwolf20-1.16#150]
* **Modpack Version**: 1.4.1

* **Issue**: Player falls through surface oil pools as if the fluid doesn't exist.
![mcoil](https://user-images.githubusercontent.com/77860037/105546986-a0bc3880-5cc3-11eb-8e94-ee626d36fe5e.PNG)

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Happens every time in SP and on a server I set up. Have uninstalled and reinstalled modpack and have tried two different PCs and still have the same behavior.

* **Mod/s Affected**: Pneumaticcraft Repressurized

* **Known Fix**: Appears to be this issue related to Forge fluids: https://github.com/NillerMedDild/Enigmatica6/issues/185

**Comment by Sunekaer** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/525
