### ISSUE TITLE
AE2 Meteor Generation Server Hang/Crash

### ISSUE THREAD

**Issue by starburn** [FTBTeam/FTB-Presents-Direwolf20-1.16#156]
* **Modpack Version**: 1.4.1

* **Issue**: AE2 meteor generation can cause server hang then crash due to vanilla generation lighting bug.

* **Link to Log or Crash File Paste**: Crash is always that tick took 60 seconds and server will close.

* **Is it Repeatable?**: Seed "love"; go to 1000 100 3000: world will not load at heart of meteor and server will hang.

* **Mod/s Affected**: AE2; issue doesn't occur with AE2 in isolation though.

* **Known Fix**: Installing appliedenergistics2-8.2.0-beta.3.jar on the server fixed the issue for now.

The developers for AE2 wrote a mixin in 8.2.0 beta 3 to address the vanilla behavior, but I have no idea what I'm talking about. See their thread: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4891

Hope this helps!

**Comment by Sunekaer** [comment]
#84
