### ISSUE TITLE
Signalum ingots stay in input slot of induction furnace after smelting

### ISSUE THREAD

**Issue by VendoAU** [FTBTeam/FTB-Presents-Direwolf20-1.16#158]
* **Modpack Version**: 1.4.1

* **Issue**: When making signalum ingots in an induction furnace they are placed in one of the input slots when they should be in the output slots, this makes it impossible to automate as the ingots can't be pulled out.

* **Is it Repeatable?**: YES

* **Mod/s Affected**: Thermal Series

* **Known Fix**: Edit the recipe

**Comment by quietust** [comment]
Is your induction smelter configured for auto-input? If so, that might be what's causing it - for whatever reason, any ingredient which can be used in a recipe will be automatically transferred from the output slot to the input slot , and signalum can be used to craft a special version of hardened glass.

**Comment by VendoAU** [comment]
> Is your induction smelter configured for auto-input? If so, that might be what's causing it - for whatever reason, any ingredient which can be used in a recipe will be automatically transferred from the output slot to the input slot , and signalum can be used to craft a special version of hardened glass.

This turned out to be the issue, turning off auto input fixed it.
Thanks for the help.
