### ISSUE TITLE
DataFixerSlayer vs. Minecolonies

### ISSUE THREAD

**Issue by uecasm** [FTBTeam/FTB-Presents-Direwolf20-1.16#159]
* **Modpack Version**: 1.4.1

* **Issue**:

According to the readme of [DataFixerSlayer](https://www.curseforge.com/minecraft/mc-mods/datafixerslayer), there are a lot of caveats about including it in a modpack without notice.  In particular upgrading any mods at all may go poorly while it is installed (if they are relying on data fixers to upgrade their tile entities between versions, for example).

In addition, a more recent version of Minecolonies than is currently present in the pack has added a warning that it will not work as expected without the data fixer system running; it apparently relies on it for proper placement of its schematics.  (And this is true even for the version that is included in the pack.)

But in general it seems like a Really Bad Idea™ to include this as standard in a modpack.

* **Link to Log or Crash File Paste**:
```
[modloading-worker-1/ERROR] [structurize/]: ----------------------------------------------------------------- 
 Invalid DataFixer detected, schematics might not paste correctly! 
The following DataFixer was added: class vazkii.dfs.FakeDataFixer
-----------------------------------------------------------------
```

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: Minecolonies, DataFixerSlayer

* **Known Fix**: Remove DataFixerSlayer

**Comment by MacChuck** [comment]
Huh, wonder if that explains the following reports:
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/54
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/139

**Comment by uecasm** [comment]
Quite likely.  Some of those screenshots were from minecolonies.

I only have a small colony and I didn't do a full MC version update, but I did observe that it was weirdly placing some blocks (most notably trying to place pistons in an already-extended state).

**Comment by uecasm** [comment]
Although having said that, I wouldn't expect it to be the cause for already-placed blocks to get messed up (other than tile entities, perhaps), as that's just blockstates that shouldn't need a fixer any more.  But it could be the cause if it's doing this with newly-placed-via-schematic blocks.

**Comment by Sunekaer** [comment]
DataFixerSlayer removed in 1.5.0
