### ISSUE TITLE
Mod disappearance

### ISSUE THREAD

**Issue by sevy7389** [FTBTeam/FTB-Presents-Direwolf20-1.16#162]
I have updated the modpack this morning to version 1.5.0. Did go well and fast. Bu surprise when I logged in no more jetpack. Check in game for mod ... not there. Go to the FTB app mod is in the list. Go to the folder mod is not there. And from the changelog it should not even have been touch.

**Comment by SonicSpeedster16** [comment]
Update to v1.5.1

**Comment by Snappiestjack** [comment]
How does something like this even occur? I've just updated our server to 1.5.0 sent out a message letting everyone know it's back up and bam 1.5.1. Each time, there's a .1 fix, maybe some tester are needed/
