### ISSUE TITLE
RfTools Builder Quarry/ShapeCard void

### ISSUE THREAD

**Issue by Arkatos** [FTBTeam/FTB-Presents-Direwolf20-1.16#164]
* **Modpack Version**: 
1.5.1
* **Issue**: 
After update to the newest version Rftools builder for clearing quarry does not work and also the same for shape card void.

I am not sure if the shape card void was working before update(didnt use) but the clearing quarry was working for all people one server so might be connected.

It just goes through all the levels and blocks but does not mine/remove blocks.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
Rftools
* **Known Fix**: 
Didn't find :(

**Comment by Parker8283** [comment]
If the area is claimed in FTB Chunks, you need to add the `rftools_builder` player to your Allies list.

**Comment by VorpalLemur** [comment]
I'm running 1.5.1 and have been using the rftools builder clearing quarry extensively both within my assigned chunks and without.   I haven't experienced this issue.   I checked my allies list and I do already have rftools_builder listed as an ally (which is something my game did automatically for me).

**Comment by Sunekaer** [comment]
As Parker said have you added the fake player to Allies list?

**Comment by Arkatos** [comment]
Ah i feel dumb now, was this new thing added in the update? i was sure it was running before this. Will close it now. Thank you and sorry
