### ISSUE TITLE
Server Crash caused by Blood Magic and Extended Caves

### ISSUE THREAD

**Issue by Danzibob** [FTBTeam/FTB-Presents-Direwolf20-1.16#165]
* **Modpack Version**: v1.5.1

* **Issue**: Going near an ExtCaves spawner structure causes a crash in Blood Magic. This is a known issue and is currently being worked on [here](https://github.com/WayofTime/BloodMagic/issues/1760). Another user on that issue specified hitting the skeleton, but the same crash was caused for me simply by going near the spawner.

* **Link to Log or Crash File Paste**: [Log 1](https://paste.feed-the-beast.com/view/cad6801a)
This log is from the above issue on the BloodMagic Github page. We the same NullPointerException in the logs on our server too.

* **Is it Repeatable?**: Yes, the server would consistently crash even when only near the spawner

* **Mod/s Affected**: Blood Magic 3.0.6-11 & ExtCaves 2.4

* **Known Fix**: Wait for an updated version of BloodMagic with the fix, apparently being released today or tomorrow (again see [linked issue](https://github.com/WayofTime/BloodMagic/issues/1760)) and use this version of the mod in the pack. WayOfTime also states that downgrading Blood Magic would fix this bug, but doesn't specify a version to downgrade to.

**Comment by Danzibob** [comment]
Blood Magic 3.1.0-15 has now been released, and fixes this problem. The new version should be added to the pack to resolve this issue.

**Comment by sadovsf** [comment]
Any eta (even rough) when pack will be updated with fix? 🤔

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0

**Comment by DeathDragonAW** [comment]
> Should be fixed in 1.6.0

Not fixed at all in 1.6.1

On the contrary, it has even become worse for us. (compared to 1.5.x)
Before it was possible to get rid of those buggy spawners using creative mode, now the server even crashes when approaching the spawner in spectator.

Players get checkmated when they get near such a spawner. Last options I see is disabling extcaves (not sure what will happen to dungeons/spawners though) or deleting the affected playerdata which really sucks for late-midgame inventories.
