### ISSUE TITLE
minecolonies breaking bug

### ISSUE THREAD

**Issue by wendictive** [FTBTeam/FTB-Presents-Direwolf20-1.16#166]
i found a bug in reason update dw20 1.50 minecolonies version 0.13.589-alpha-universal. 
my hole town is medeval dark Oak and now when i try updating a darkoark building it want to upgrade to the oak vesion and that doesent look the same at all so builder wants new material but just stands ther and does nothing ,,, im guessing the dimentions of the 2 build are not the same

* **Modpack Version**: 
dw20 1.50 minecolonies version 0.13.589-alpha-universal. 
* **Issue**: 
minecolonies creater Raven derped ,,, he is fixing as fast as possible
* **Link to Log or Crash File Paste**: 
no crash
* **Is it Repeatable?**: 

* **Mod/s Affected**: 
minecolonies
* **Known Fix**: 
downgrade minecolonies til developer has a fix

**Comment by wendictive** [comment]
here is fix .. please update dw20

https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3185028

**Comment by KroniK907** [comment]
+1 to please update minecolonies to fix this bug.

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
