### ISSUE TITLE
Client crash caused by Mekanism with optifine

### ISSUE THREAD

**Issue by sadovsf** [FTBTeam/FTB-Presents-Direwolf20-1.16#167]
* **Modpack Version**: 1.5.1

* **Issue**: Client is crashing when Mekanism basic fluid tank is right clicked with bucket containing liquid when full or with empty hand anytime.
* 

* **Is it Repeatable?**: Every time

* **Mod/s Affected**: Based on response from Mekanism author it may be caused by some rendering fun in optifine:
https://github.com/mekanism/Mekanism/issues/6930

* **Known Fix**: Did not try to search for any, being careful when dealing with these tanks sort of works. Probably disabling optifine would work

**Comment by quietust** [comment]
Optifine isn't part of this pack, so by adding it you're pretty much accepting responsibility for any problems it might cause.

**Comment by sadovsf** [comment]
Aah, I totally forget that I did install it myself 🤦‍♂️
My bad, thank you for your time

**Comment by Sunekaer** [comment]
We dont support optifine, please recreate the issue without it

**Comment by sadovsf** [comment]
I was not able to so probably related to optifine specifically. You can close this then. Thank you once more
