### ISSUE TITLE
Unable to Craft Mining Turtles Both Normal and Advanced

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Presents-Direwolf20-1.16#17]
* **Modpack Version**: 1.0.0

* **Issue**: Unable to Craft Mining Turtles Both Normal and Advanced,
* can see recipes in JEI but will not craft
**JEI:**
![image](https://user-images.githubusercontent.com/3998288/102715146-35013d00-42cb-11eb-8f6f-df07b7cf438b.png)
 **Crafting:**
 ![image](https://ss1.manmaed.net/1608472669.png)
 ![image](https://ss1.manmaed.net/1608472733.png)

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yep SP and MP

* **Mod/s Affected**: CC:Tweeked

* **Known Fix**: IDK

* **Note**: Other Turtles are Unaffected

**Comment by Sunekaer** [comment]
Works for me and other testers, please reinstall the pack and test or with the newest version of the pack

**Comment by manmaed** [comment]
Worked in SP #Closed
