### ISSUE TITLE
Warp Stone no longer works since update to 1.16 - 1.5.1

### ISSUE THREAD

**Issue by LisaLC2712** [FTBTeam/FTB-Presents-Direwolf20-1.16#170]
* **Modpack Version**: Direwolf20 1.16 - 1.5.1

* **Issue**: Waystones existed and were known to me.  Warp stone was working to teleport to the waystones.  After update to 1.5.1, warp stone will make its sound (like is it going to work), but does not prompt you for a waystone selection.  Animation and sound with the warp stone works, but nothing else happens.   

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**:  I was able to repeat error.  Verified waystones were still linked to one another.  Even added a new waystone to ensure that aspect was working properly.  Issue seems to be limited to the warp stone.  Had others on the server confirm and repeat the issue I was having.  Same results.

* **Mod/s Affected**:  No known conflicts.  Issue seems to be isolated to Waystones mod

* **Known Fix**: none

**Comment by boballama** [comment]
You need to empty your off hand.  Like no torches in your left hand!
