### ISSUE TITLE
killing multiple skeletons causes game crash

### ISSUE THREAD

**Issue by briggsmech** [FTBTeam/FTB-Presents-Direwolf20-1.16#172]
I set up a mob farm using two skeleton spawners and mob grinding utilities. Every time I kill more than one skeleton the game crashes.
I have just updated to version 1.5.1

[crash-2021-01-27_20.44.35-server.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5899220/crash-2021-01-27_20.44.35-server.txt)

**Comment by Ironcanon** [comment]
[crash-2021-01-31_09.37.28-server.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5899510/crash-2021-01-31_09.37.28-server.txt)
Having the exact same crash, except I crash as soon as I hit the skeletons. 

No sure if it matters but my skeleton spawner was from an extcaves world gen dungeon.

**Comment by LezChap** [comment]
Looks like the same issue as #165.  Looks like manually updating Blood Magic (client and server) should solve the problem until the pack updates with the new version.
