### ISSUE TITLE
Update IF version to fix client crashing bug

### ISSUE THREAD

**Issue by EternalClickbait** [FTBTeam/FTB-Presents-Direwolf20-1.16#173]
* **Modpack Version**: 1.3.1 - 1.5.1 (current)

* **Issue**: Detailed [here](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/977) on IF github

* **Link to Log or Crash File Paste**: See link above
* **Is it Repeatable?**: Yes, I crash every single time  I join

* **Mod/s Affected**: Industrial Foregoing 3.2.8.2, 

* **Known Fix**: Update IF Version? Was told to do so by mod author, but have been unable to test due to not hacing access to update server as well, and I cannot reproduce (so far) on singleplayer.

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
