### ISSUE TITLE
Feature Request: Ice/Packed Ice/Blue Ice work w/ Compacting Drawers

### ISSUE THREAD

**Issue by sitedyno** [FTBTeam/FTB-Presents-Direwolf20-1.16#174]
* **Modpack Version**: 1.5.1 

* **Issue**: Feature Request Ice/Packed Ice/Blue Ice work w/ Compacting Drawers. I ASSume this can be configured to work? 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A 

* **Mod/s Affected**: Storage Drawers 

* **Known Fix**: N/A

**Comment by quietust** [comment]
One problem with this is that it'd allow compacting drawers to be used to _unpack_ blue ice into packed ice and packed ice into normal ice, something which probably isn't meant to be possible.

**Comment by sitedyno** [comment]
That's a valid point I hadn't considered. Why would anyone `want` to do that? I want the blue ice for Powah.

**Comment by Sunekaer** [comment]
this wont be added
