### ISSUE TITLE
Packet size is bigger than allowed. Fresh out the box server

### ISSUE THREAD

**Issue by Hamilegit** [FTBTeam/FTB-Presents-Direwolf20-1.16#176]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed
