### ISSUE TITLE
Crash on start, failed to find resource forge-1.16.4-35.1.36-client.jar

### ISSUE THREAD

**Issue by LinusOP** [FTBTeam/FTB-Presents-Direwolf20-1.16#178]
* **Modpack Version**: 1.5.1

* **Issue**: The game crashes immediately as I press start in the minecraft launcher. It is a completely fresh install of both the FTB App and the modpack (First time playing, just installed it all, have not had a successful boot so far).
It fails to find the file at `AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.16.4-35.1.36\forge-1.16.4-35.1.36-client.jar`, see log paste below.
In that directory I have the two following files: `forge-1.16.4-35.1.36.jar` and `forge-1.16.4-35.1.36-universal.jar`

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7aca9028

* **Is it Repeatable?**: Presumably, by not having the file in the directory.

**Comment by Sunekaer** [comment]
Try and delete AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.16.4-35.1.36 install the pack again, and see if it works

**Comment by LinusOP** [comment]
> Try and delete AppData\Local.ftba\bin\libraries\net\minecraftforge\forge\1.16.4-35.1.36 install the pack again, and see if it works

This seems to have worked! However when I reinstalled that was version 1.6.0 of the pack, not 1.5.1 (as that was seemingly released after I opened the issue), so perhaps that fixed it? (Although that feels less likely)
Nevertheless the client jar now shows up and the pack launchs, much appreciated 😄
