### ISSUE TITLE
The infinity hammer wont accept looting enchantment The question is (why?)

### ISSUE THREAD

**Issue by wain99** [FTBTeam/FTB-Presents-Direwolf20-1.16#179]
Not a Bug its just an annoying thing

* **Modpack Version**:
Version 1.16 - 1.5.1
* **Issue**:
The Infinity hammer is an amazing weapon but including fortune to a weapon is just wrong you can't use it to mine anything useful or benefit from it in any shape or form .
The point is if you just add the looting enchantment to the hammer that would be amazing.
it wont make it overpowered it just would make it bit convenient better than a week sword with looting that takes 3 to 4 hits to kill an enderman

Thanks In advance

**Comment by Sunekaer** [comment]
This would be a question for the mod author: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues
