### ISSUE TITLE
Crash when viewing mod list

### ISSUE THREAD

**Issue by SonicSpeedster16** [FTBTeam/FTB-Presents-Direwolf20-1.16#18]
* **Modpack Version**: 1.0.0

* **Issue**: After starting the pack and clicking the Mods button, I was going through the list and clicking on several mods I wasn't familiar with. After a few minutes I got a crash to desktop.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4ee8bd7c

* **Is it Repeatable?**: Yes, several times.

* **Mod/s Affected**: Unknown.

* **Known Fix**: Don't go through the modlist ingame.

**Comment by Sunekaer** [comment]
Weird, could you test with FTB App and not multimc?
Just wanna make sure its not multimc doing something weird, as this is the first time i see this issue

**Comment by SonicSpeedster16** [comment]
I just tried it using the FTB App instead of MultiMC and it crashed again: https://paste.feed-the-beast.com/view/0357380e

It seems to be related to Simply Backpacks. The last couple of crashes I noticed were when I clicked on it in the mods list.

**Comment by Sunekaer** [comment]
hmm thanks for testing.
Ill ask around if anyone has seen this issue before

**Comment by SonicSpeedster16** [comment]
Thanks. I did test in a new instance with only Forge and Simply Backpacks installed, and couldn't get it to crash. Really weird.

**Comment by Sunekaer** [comment]
Yeah i think the only way to find it is by adding mods back slowly til you find it

**Comment by Sunekaer** [comment]
Could you let me know which mods gives you the crash then clicking them?
