### ISSUE TITLE
Tools with Excavate & Fortune enchants don't fortune

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Presents-Direwolf20-1.16#180]
* **Modpack Version**: 1.5.1

* **Issue**: Tools with both excavate & fortune enchants ignore the fortune bonus.

* **Is it Repeatable?**: yes, in sp and mp

* **Mod/s Affected**: Cyclic

* **Known Fix**: Already reported to the Cyclic dev and looks like they have an updated version with a fix available.

**Comment by Sunekaer** [comment]
Should be fixed in 1.6.0
