### ISSUE TITLE
Large Ram usage

### ISSUE THREAD

**Issue by x4dr** [FTBTeam/FTB-Presents-Direwolf20-1.16#181]
* **Modpack Version**: 1.5.1

* **Issue**: Modpack uses more than 5.5 GB
Other modpacks (ran Revelation before, without issues) used about 3, up to 4GB, this one i had to up the ram to 5.5 to stop it from running out of ram on startup. After a few hours, it still goes over and crashes.

* **Link to Log or Crash File Paste**: Creeper Host just informed me that the instance ran out of memory and had to be restarted

* **Is it Repeatable?**: host on a system with less than 5GB available RAM and it will crash

* **Mod/s Affected**: 

* **Known Fix**: pay more money to hoster for a lot more cpu, a lot more drive space and a tiny bit more ram

**Comment by Sunekaer** [comment]
Nothing i can do about this, Minecraft is getting more and more ram/CPU heavy with each update
