### ISSUE TITLE
Clicking on refined storage detector with sulfur will crash the game

### ISSUE THREAD

**Issue by wain99** [FTBTeam/FTB-Presents-Direwolf20-1.16#183]
Version 1.16 -1.5.1 

Clicking a refined storage detector with sulfur will crash the game (the detictor may need to be connected to a used refined storage)
The link to the crash report :
https://paste.feed-the-beast.com/view/6ada8838

The bug is very easily repeatable

not any huge problem or corrupts any thing It just crashes the game after you click it

**Comment by Sunekaer** [comment]
please test with 1.6.0

**Comment by wain99** [comment]
I tested it and crashed again in 1.6.0

this appeared

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=connected, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{refinedstorage:detector}
Exit Code: -1
