### ISSUE TITLE
Industrial Foregoing milk not compatible with milk buckets

### ISSUE THREAD

**Issue by NeosGhost** [FTBTeam/FTB-Presents-Direwolf20-1.16#184]
Milk from industrial foregoing has invalid milk tag values and localization.

* **Modpack Version**: 1.5.1

* **Issue**: Milk from industrial foregoing has invalid milk tag values and localization causing liquid based crafting (immersive engineering assembler) to not function. 
* **Is it Repeatable?**: Is repeatable in creative and survival

* **Mod/s Affected**: Industrial foregoing...Immersive engineering

* **Known Fix**: This is fixed in Industrial Foregoing version 3.2.8.4 so the pack just needs a mod update.
Thanks
![image](https://user-images.githubusercontent.com/16095247/106893130-b6adfe00-66b2-11eb-89d7-86590f9bcb42.png)

**Comment by Sunekaer** [comment]
fixed in 1.6.0
