### ISSUE TITLE
Underground skeleton spawner cages crash server

### ISSUE THREAD

**Issue by Hamilegit** [FTBTeam/FTB-Presents-Direwolf20-1.16#186]
* **Modpack Version**: 1.5.1
* 
* **Issue**: When a player breaking the spawner  in these underground cages the server crashes. It has happened 3 times so far on our server 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b0dca82e

* **Is it Repeatable?**: As I said it has happened 3 times so yes its repeatable 

* **Mod/s Affected**:  Crash log says bloodmagic but im not sure if it is

* **Known Fix**:

**Comment by SonicSpeedster16** [comment]
Duplicate of #165 . Update the pack to version 1.6.0 it should be fixed.

**Comment by Hamilegit** [comment]
thank you i will do that hopefully it works

**Comment by Hamilegit** [comment]
ill keep this open till i update and test it out will let oyu know

**Comment by Hamilegit** [comment]
Question, Can i upgrade my server to 1.6.0 without corruption and stuff?

**Comment by billybricker** [comment]
> Question, Can i upgrade my server to 1.6.0 without corruption and stuff?

Most likely but always make a backup before making any changes to the server just in case.

**Comment by Hamilegit** [comment]
Thank you that update worked I will close now
