### ISSUE TITLE
Extreme Reactors 2 Guide Book crafting issue

### ISSUE THREAD

**Issue by alfw** [FTBTeam/FTB-Presents-Direwolf20-1.16#187]
* **Modpack Version**: 1.5.1 , 1.6.0

* **Issue**: When trying to craft the **The Extreme Book** guide book you get back the item **item.patchouli.guide_book** with no NBT tags. 

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**:  SSP and SMP

* **Mod/s Affected**: ExtremeReactors2 , KubeJS

* **Known Fix**: This is a scripting error in the KubeJS recipes in file `kubejs\server_scripts\recipes\bigreactors.js`.

The problem is that with the use of ``Item.of()`` where the NTB data is set in the amount of returned items. Doing the change under are fixing the NTB data for the book and it works! 

`event.shapeless(Item.of('patchouli:guide_book', {"patchouli:book":"bigreactors:erguide"}), ['minecraft:book', '#forge:ingots/uranium'])`
To:
`event.shapeless(Item.of('patchouli:guide_book', 1).withNBT({"patchouli:book":"bigreactors:erguide"}), ['minecraft:book', '#forge:ingots/uranium'])
`

PS: If you run a server you can do this _patch_ only on the server.

**Comment by ZeroNoRyouki** [comment]
Just for info, I've added an alternative recipe for the book that use forge:ingots/uranium to craft it in ER 2.0.22
