### ISSUE TITLE
Unable to access mining dimension after update to 1.6.0

### ISSUE THREAD

**Issue by sadovsf** [FTBTeam/FTB-Presents-Direwolf20-1.16#188]
* **Modpack Version**: 1.6.0

* **Issue**: When i want to access mining dimension on server where it was working on 2 previous versions i get only chat message "Invalid world ID set". Crafting new mining dimension portal block does not solve it

* **Is it Repeatable?**: Every time

* **Mod/s Affected**: Just Another Mining Dimension

* **Known Fix**: Did not find any

**Comment by sadovsf** [comment]
Same issue applies to void dimension block

**Comment by sadovsf** [comment]
And just tested it and same applies to single player as well

**Comment by Inzaniity** [comment]
From what I heard another restart of the game / server does fix it...

**Comment by Hadoukanen** [comment]
Indeed it seems so. a second restart works.

**Comment by Alex-Irwin** [comment]
> 
> 
> Indeed it seems so. a second restart works.

I can confirm a restart fix this issue for me as well.

**Comment by sadovsf** [comment]
Me too, restart helped. Thank you, closing this
