### ISSUE TITLE
Building Gadgets crashes SP world when trying to place a 7x7 square

### ISSUE THREAD

**Issue by schattennarr** [FTBTeam/FTB-Presents-Direwolf20-1.16#189]
* **Modpack Version**: 1.6.0

* **Issue**: I am in a Flatworld in Creative wanting to test Building Gadgets. After changing the mode from "Build to me" to a plain 7x7 square and right clicking the client crashes. I have changed my bindings to Numpad 1-8. I loaded the pack via MultiMC.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/fc556e5f

* **Is it Repeatable?**: Yes

**Comment by Sunekaer** [comment]
Should be fixed in newer version
