### ISSUE TITLE
[1.16.x] Suggested Config & KubeJS changes

### ISSUE THREAD

**Issue by MacAttack-UK** [FTBTeam/FTB-Presents-Direwolf20-1.16#19]
Here are a few changes I've made on my private server which are mainly QoL and thought I would share and maybe save someone some time, although I'm sure you guys have already done these for the next version.

_23-12-2020 I've updated the compacting rules adding PSI Dust/Dust Block and removed a Mekanism recipe entry._

* **Modpack Version**: 1.1.2

storagedrawers-common.toml - Add Mini Coal/Charcoal, Raw Uraninite & PSI Dust to compacting drawers

`compactingRules = ["minecraft:clay, minecraft:clay_ball, 4", "minecraft:coal, minicoal2:minicoal, 8", "minecraft:charcoal, minicoal2:minicharcoal, 8", "powah:uraninite_raw_dense, powah:uraninite_raw, 2", "powah:uraninite_raw, powah:uraninite_raw_poor, 2", "psi:psidust_block, psi:psidust, 9"]`

MyDW20Fixes.js - Integrate missing Thermal, Powah & Mana and Artifice to Mekanism machines

`    //Mekanism
    event.recipes.mekanism.enriching(item.of('thermal:silver_dust', 2), '#forge:ores/silver')
    event.recipes.mekanism.enriching(item.of('thermal:nickel_dust', 2), '#forge:ores/nickel')
    event.recipes.mekanism.enriching(item.of('mana-and-artifice:vinteum_dust', 2), 'mana-and-artifice:vinteum_ore')
    event.recipes.mekanism.crushing(item.of('thermal:silver_dust'), 'thermal:silver_ingot')
    event.recipes.mekanism.crushing(item.of('thermal:nickel_dust'), 'thermal:nickel_ingot')
    event.recipes.mekanism.crushing(item.of('mana-and-artifice:vinteum_dust'), 'mana-and-artifice:vinteum_ingot')
    event.recipes.mekanism.smelting(item.of('powah:uraninite', 4), 'powah:uraninite_raw_dense')
`
    ~~event.recipes.mekanism.smelting(item.of('mana-and-artifice:vinteum_ingot'), 'mana-and-artifice:vinteum_dust')~~
I've removed this last entry as it just straight up breaks the mod!!

Hope you find these useful,

Mac :)

**Comment by Sunekaer** [comment]
Thanks for the suggestion Mac, I will look at them after the holidays

**Comment by shubidubapp** [comment]
Uh. I might have a few QoL suggestions too. But sadly I have no knowledge for actually implementing those, maybe adding it to recipes in the mod files itself? since to my knowledge KubeJS doesn't support Powah.

For Powah
As energizing recipes:

Blazing Crystal Block:

        Output: powah:blazing_crystal_block
        Input: botania:blaze_block 
        Energy Cost: 810000 FE

Energized Steel Block:

        Output: powah:energized_steel_block , Amount: 2
        Input: #forge:storage_blocks/gold
        Input: #forge:storage_blocks/iron
        Energy Cost: 90000 FE

Well I think the above 2 is enough. Since those are the ones I think most used ones and most of the time hand crafted in the early game. But just for the sake of doing it.

Charged Snowball:

        Output: powah:charged_snowball, Amount: 4
        Input: forge:snow_block
        Energy Cost: 2000000 FE

Block of Niotic Crystal:

        Output: powah:niotic_crystal_block
        Input: #forge:storage_blocks/diamond
        Energy Cost: 2700000 FE

Block of Spirited Crystal:

        Output: powah:spirited_crystal_block
        Input: #forge:storage_blocks/emerald
        Energy Cost: 9000000 FE

The energy costs are just multiplied with the result amount compared to the original recipes.

**Comment by Sunekaer** [comment]
> event.recipes.mekanism.smelting(item.of('powah:uraninite', 4), 'powah:uraninite_raw_dense')

This one already exists, the rest looks fine.

**Comment by Sunekaer** [comment]
> Uh. I might have a few QoL suggestions too. But sadly I have no knowledge for actually implementing those, maybe adding it to recipes in the mod files itself? since to my knowledge KubeJS doesn't support Powah.
> 
> For Powah
> As energizing recipes:
> 
> Blazing Crystal Block:
> 
> ```
>     Output: powah:blazing_crystal_block
>     Input: botania:blaze_block 
>     Energy Cost: 810000 FE
> ```
> 
> Energized Steel Block:
> 
> ```
>     Output: powah:energized_steel_block , Amount: 2
>     Input: #forge:storage_blocks/gold
>     Input: #forge:storage_blocks/iron
>     Energy Cost: 90000 FE
> ```
> 
> Well I think the above 2 is enough. Since those are the ones I think most used ones and most of the time hand crafted in the early game. But just for the sake of doing it.
> 
> Charged Snowball:
> 
> ```
>     Output: powah:charged_snowball, Amount: 4
>     Input: forge:snow_block
>     Energy Cost: 2000000 FE
> ```
> 
> Block of Niotic Crystal:
> 
> ```
>     Output: powah:niotic_crystal_block
>     Input: #forge:storage_blocks/diamond
>     Energy Cost: 2700000 FE
> ```
> 
> Block of Spirited Crystal:
> 
> ```
>     Output: powah:spirited_crystal_block
>     Input: #forge:storage_blocks/emerald
>     Energy Cost: 9000000 FE
> ```
> 
> The energy costs are just multiplied with the result amount compared to the original recipes. It will basically take same amount of time. Same amount of FE, same amount of ingredients. Just less manual labor...

I talked with Dire and these recipes wont be added as he wanted to keep mods to be as true to the defaults as possible
