### ISSUE TITLE
Minecolonies failing to function

### ISSUE THREAD

**Issue by MirceaZisu** [FTBTeam/FTB-Presents-Direwolf20-1.16#190]
* **Modpack Version**: 1.6.0

* **Issue**: Minecolonies failing to function. After updating to 1.6.0, my builders have failed to function. All of the other colonists are still working. 

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Unsure, but I think that there are other issues currently taking precedent.

* **Mod/s Affected**: Minecolonies

* **Known Fix**: ?

**Comment by Sunekaer** [comment]
Could you check with 1.6.1?

**Comment by MirceaZisu** [comment]
Will try as soon as our server gets updated.

**Comment by MirceaZisu** [comment]
> Could you check with 1.6.1?

I think the issue boiled down to mythicbotany for that too. My builders work now on their own.
