### ISSUE TITLE
Critting any entity results in invincibility/undead

### ISSUE THREAD

**Issue by S0und16** [FTBTeam/FTB-Presents-Direwolf20-1.16#191]
* **Modpack Version**: 1.6.0

* **Issue**: Whenever any entity (including players!) is crit, whether with a weapon or empty hand, they become invincible. I'm on a server, and when my friend crits me I become "dead". I can't take damage or die from /kill, mobs ignore me, accessing inventories or any block ui immediately exits that ui, can't pick up items, etc. Also, there are no animations for players

* **Is it Repeatable?**: I'm pretty sure the bug occurs any time a mob is crit.

* **Known Fix**: The only way we could fix this was by deleting the entity data for any affected players/entities
 from the server.
![2021-02-04_16 53 06](https://user-images.githubusercontent.com/35081136/106965973-7bdbb280-6712-11eb-9423-a0aa438ebe57.png)

**Comment by S0und16** [comment]
Update: This doesn't happen very often with other mobs, but in our experience it happens 100% of the time for players.

**Comment by MirceaZisu** [comment]
This issue should be closed as duplicate. See #185
