### ISSUE TITLE
Server crash when hitting hostile mob. (Ver 1.5.1)

### ISSUE THREAD

**Issue by TheDarkPreacher** [FTBTeam/FTB-Presents-Direwolf20-1.16#192]
Pack Version: 1.5.1

Issue: Hard server crash when hitting hostile mob, ticking entity error.

Crash log: https://pastebin.com/CnVb1WsT

According to stack trace, error is caused by Blood Magic. Not sure if issue was reported or fixed in 1.6.0, waiting until confirmation before updating my server to that.

**Comment by Sunekaer** [comment]
fixed in 1.6.0
