### ISSUE TITLE
Mobs dont die when hit by crit.

### ISSUE THREAD

**Issue by ByArchery** [FTBTeam/FTB-Presents-Direwolf20-1.16#194]
https://user-images.githubusercontent.com/14233929/107065202-7df15000-67aa-11eb-8179-bd193cf93459.mp4

When u try to kill a any mob with a crit and the hp become 0 the mob dont die, but when u kill them normal without crit they die like normally

I attach a small video with the bug

im on the latest version of Direwolf20 1.16, version 1.6.0

**Comment by billybricker** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/185
