### ISSUE TITLE
Player not dieing. Invincible Player bug. Game breaking.

### ISSUE THREAD

**Issue by SultanGabriel** [FTBTeam/FTB-Presents-Direwolf20-1.16#195]
* **Modpack Version**: 1.6.0 - just updated today
* **Issue**: I play on a server hosted on my pc with a friend. He killed me while i was in looking up a recipe in JEI. As I was supposed to die ( got no hearts left ). My screen started shaking, my player was red, maybe the animation played when you die stopped in the middle. ( Look up GIF I put below )
* **Other things**: I tried the /kill command but that didn't do anything, it just printed the text in the conosole. I have tried to jump in the void but that didn't kill me either. My friend wasn't able to deal any more damage. It was like I was invincible. I was able to eat something. I couldn't open any chests, crafting tables or blocks. The walking animation dissapearred and my player was just sliding. 
* **Link to Log or Crash File Paste**: N/A because my game didn't crash and in the server console there wasn't anything related.
* **Is it Repeatable?**: I've seen this happening to mobs when being critically hit when they were supposed to die. #185 #194 
* **Known Fix**: Nothing known so far.. I've tried a few things as said above.

* **Images**

![1](https://user-images.githubusercontent.com/24797672/107067484-a0ea2700-67df-11eb-8e3a-9c18e3199bc8.PNG)
![2](https://user-images.githubusercontent.com/24797672/107067476-9fb8fa00-67df-11eb-8aa7-b858e8051552.PNG)
![2021-02-05 18-30-13](https://user-images.githubusercontent.com/24797672/107068331-c62b6500-67e0-11eb-8000-e8d393e56aea.gif)

**Comment by billybricker** [comment]
Did you try updating MythicBotany like it says at the end of #185?

**Comment by SultanGabriel** [comment]
> Did you try updating MythicBotany like it says at the end of #185?

Yup that fixed it. Thank you !

**Comment by Hamilegit** [comment]
might want to put that in a hot fix instead of getting people to download it individually and getting other server folk to do the same
