### ISSUE TITLE
Enemies become invulnerable

### ISSUE THREAD

**Issue by axeldavenport12** [FTBTeam/FTB-Presents-Direwolf20-1.16#198]
I've been playing the newest 1.16 pack

Sometimes when I hit an enemy, I believe it's when I do critical damage to it, it becomes unkillable. The hearts in the top display shows it has no hearts and the mob just slides around the world with no animations. I can't kill it in creative and for creepers they will cease to explode. 

Thank you!

**Comment by LezChap** [comment]
Update to 1.6.1, should fix the problem.
