### ISSUE TITLE
Garden cloche duplication using Sack of Holding

### ISSUE THREAD

**Issue by StvnWthrsp** [FTBTeam/FTB-Presents-Direwolf20-1.16#199]
You can use the Sack of Holding (Cyclic) to pick up a single block of the 3 block tall Garden Cloche (Immersive Engineering). The Garden Cloche will continue to function as normal. You can then use the Sack of Holding again to place that single block somewhere else. Breaking this single block then places a new Garden Cloche in your inventory. You can also break the original Garden Cloche and place it down again to restore the missing block. In fact, you can do this with two blocks from a single Garden Cloche to duplicate a single item into three.
![garden_cloche_bug](https://user-images.githubusercontent.com/23327031/107126039-68982680-687b-11eb-9d49-a9848786cc32.PNG)

**Comment by SonicSpeedster16** [comment]
This should be fixable by adding the Cloche to the Sack of Holding Blacklist config. The Cloche was included in the blacklist by default in previous versions but apparently no longer is in 1.16 (see https://github.com/Lothrazar/Cyclic/issues/1099).
