### ISSUE TITLE
Error rendering Chest GUI

### ISSUE THREAD

**Issue by Atagait** [FTBTeam/FTB-Presents-Direwolf20-1.16#2]
* **Modpack Version**: 1.0

* **Issue**: Chests cannot be opened

* **Link to Log or Crash File Paste**:
https://paste.feed-the-beast.com/view/4efe9634

[16Dec2020 23:38:12.533] [Render thread/WARN] [net.minecraft.client.gui.ScreenManager/]: Failed to create screen for menu type: minecraft:generic_9x6

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: minecraft

**Comment by Sunekaer** [comment]
Hmm thats very weird, never seen that before.
Did you try restarting the game?
If yes to the restart, could you try and open the instance folder go to mods folder and remove mouse tweaks and see if you still have the issue?

**Comment by Atagait** [comment]
I restarted it today and it seems to have fixed itself, though restarts yesterday didn't. Odd
