### ISSUE TITLE
RF Tools Build does not working correctly 

### ISSUE THREAD

**Issue by Terminator81** [FTBTeam/FTB-Presents-Direwolf20-1.16#20]
when I use the RF TOOLS Builder, it does not work when I use the CLEARING CARD.

Strangely, the normal quary card works partially, i.e. ores are mined but not replaced by dirt.

**Comment by Terminator81** [comment]
Does someone have the same problem?

**Comment by MacChuck** [comment]
Pack version 1.1.1, I was able to use the builder with a clearing quarry card as expected.

**Comment by Terminator81** [comment]
OK i will try again

**Comment by Terminator81** [comment]
now it gets weird. when i try it in a creative world, it works. If I go back to my server, it doesn't. Here now not even the message comes when right clicking with the map on the builder

**Comment by Terminator81** [comment]
after restarting server i can click again but the builder does not mine anything :(
