### ISSUE TITLE
Minecolonies claimed chunks supersedes fake player settings from FTBChunks

### ISSUE THREAD

**Issue by timothyCoxon** [FTBTeam/FTB-Presents-Direwolf20-1.16#201]
* **Modpack Version**: Latest

* **Issue**: As the title suggests

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mine Colonies and any other mod that breaks/places blocks. (Modular routers and Industrial forgoing 

* **Known Fix**: There is a setting in the Server Config that allows for turning the "colony protection system" off. It's an anti-griefer setting in multi-player situations... I don't know if more of your users are single player rather than server managers but It would seem logical that this setting be opt-in as a server manager should be far more technically competent compared to the average single player ;)

**Comment by Asherslab** [comment]
Note: MineColonies also has Fake Player settings inside the TownHall block. It also has chunkloading / etc. My recommendation would be to use those features instead

**Comment by Sunekaer** [comment]
Nothing i can about this, use the build-in MineColonies or open an issue with MineColonies
