### ISSUE TITLE
Undergarden Terrain Generation

### ISSUE THREAD

**Issue by xorgrin** [FTBTeam/FTB-Presents-Direwolf20-1.16#202]
Had an issue on our Direwolf20 server with undergarden generation so I thought maybe its just our current world or something that was causing the issue so I downloaded a fresh copy of the server of Direwolf20 1.16 1-6-1 and created a portal to the Undergarden. It looks exactly the same as it did on our current server. There are mobs and regular terrain. But I don't see any growth, no ore at all. Here are 2 examples. Based on videos I have seen this isn't how its supposed to look.
I've found catacombs that contain chests and mobs but other than that its just blocks, no vines, no vegetation at all. I reported this in the undergarden mod github as well I'm not sure where it falls but I'm wondering if anyone else had this issue.
![2021-02-08_10 04 55](https://user-images.githubusercontent.com/78618804/107238404-cea8b900-69f5-11eb-989f-c45de3f1283b.png)
![2021-02-08_10 05 05](https://user-images.githubusercontent.com/78618804/107238409-cfd9e600-69f5-11eb-8d72-4f79628db747.png)
![2021-02-08_10 08 57](https://user-images.githubusercontent.com/78618804/107238410-d0727c80-69f5-11eb-8be9-538f56ee13c3.png)
![2021-02-08_10 04 02](https://user-images.githubusercontent.com/78618804/107238415-d1a3a980-69f5-11eb-8137-f9e3e5fe42e6.png)
![2021-02-08_10 04 40](https://user-images.githubusercontent.com/78618804/107238421-d23c4000-69f5-11eb-8f09-3e1ed1e9fd83.png)

1.6.1

Undergarden Terrain Generation

**Comment by Decarroll** [comment]
I have the same issue.

**Comment by xorgrin** [comment]
The dev of undergarden asked me if immersive engineering was part of the pack (which it is). I told him it was and that was the last I heard so I guess its a mod conflict with that? Hopefully one way or another they will resolve it.

**Comment by 2xMJet** [comment]
> The dev of undergarden asked me if immersive engineering was part of the pack (which it is). I told him it was and that was the last I heard so I guess its a mod conflict with that? Hopefully one way or another they will resolve it.

Temporary solution: downgrade Immersive Engineering from 4.2.1-131 to 4.2.0-130 and regenerate undergarden dimension. Worked for our server. Issue is known for IE dev, and should be patched in th next mod version.

**Comment by Sunekaer** [comment]
fixed in 1.7.0
