### ISSUE TITLE
Just another void/mining dim(ension) - not updated for 1.16.5

### ISSUE THREAD

**Issue by Joinatic** [FTBTeam/FTB-Presents-Direwolf20-1.16#203]
* **Modpack Version**: 1.6.1

* **Issue**: Updated from 1.5.1 to 1.6.1 and the Void and Mining Dimension were gone. (mods: javd and jamd)

* **Link to Log or Crash File Paste**: no logs

* **Is it Repeatable?**: Just try to use one of the dimensions.

* **Mod/s Affected**: 
* - Just Another Void Dim: https://www.curseforge.com/minecraft/mc-mods/jei
* - Just Another Mining Dimension: https://www.curseforge.com/minecraft/mc-mods/jamd

* **Known Fix**: Update to the Version that is supported for 1.16.5 I guess.

**Comment by SonicSpeedster16** [comment]
Do you mean the mods are missing or that you can't access the dimensions?

Try restarting the server/game and trying to access the dimension again : #188.

**Comment by Joinatic** [comment]
Yes this worked! Sorry couldn't find this issue. Thank you very much!
