### ISSUE TITLE
Mineralis Ritual from Astral only generates basic ores [fix included]

### ISSUE THREAD

**Issue by mivalsten** [FTBTeam/FTB-Presents-Direwolf20-1.16#204]
* **Modpack Version**: 1.5.1

* **Issue**:  Astral Sorcery is not configured properly, and because of that, mineralis ritual only generates ores from vanilla minecraft

* **Link to Log or Crash File Paste**: not a bug

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Astral Sorcery

* **Known Fix**:

Update this setting in `defaultconfigs/astralsorcery.toml`

Those values were generated by running RFTools Builder in Overworld plains biome for about 30 minutes. Amount of emeralds was ballparked, same with netherite.

```
mineralis_ritual_ore = [
			"forge:ores/coal;6000",
			"forge:ores/iron;3600",
			"forge:ores/gold;330",
			"forge:ores/lapis;134",
			"forge:ores/redstone;1100",
			"forge:ores/emerald;120",
			"forge:ores/diamond;110",
			"forge:ores/netherite_scrap;20",
			"forge:ores/osmium;940",
			"forge:ores/uranium;600",
			"forge:ores/fluorite;970",
			"forge:ores/uranite_poor;690",
			"forge:ores/uranite;280",
			"forge:ores/uranite_dense;30",
			"rftoolsbase:dimensionalshard_overworld;125",
			"forge:ores/zinc;1550",
			"forge:ores/aluminum;210",
			"astralsorcery:rock_crystal_ore;1",
			"forge:ores/apatite;380",
			"forge:ores/cinnabar;100",
			"forge:ores/sulfur;110",
			"forge:ores/copper;770",
			"forge:ores/tin;755",
			"forge:ores/lead;320",
			"forge:ores/silver;270",
			"forge:ores/nickel;160",
			"forge:ores/niter;115",
			"forge:ores/certus_quartz;930"
			]
			```

**Comment by quietust** [comment]
It shouldn't generate rock crystal ore, since that's part of Astral Sorcery itself and has its own means of acquisition - if it were meant to be possible, the mod would be doing it already. Similarly, ancient debris probably shouldn't be in there either.

For reference, the builtin rarity values are as follows;
* Coal: 5200
* Iron: 2500
* Gold: 440
* Lapis: 200
* Redstone: 600
* Emerald: 60
* Diamond: 40

**Comment by mivalsten** [comment]
I do not agree, at least partially. If this ritual is to serve as an ore generation method, it must generate all resources. As you can see, rock crystal ore has a rarity of 1 so it will spawn almost impossibly rare. Same with netherite, as those are rare resources. And with pack having such op blocks are mekanism digital miner, I don't see a problem with big ritual that you need to progress to, build multiple multiblocks, spend at least an hour farming good crystals and then it has a chance to just break in time.

**Comment by quietust** [comment]
If you think the Mineralis ritual should generate rock crystal ore, then I'd recommend submitting a bug report for Astral Sorcery itself - either it's a bug or a deliberate omission, and either would be useful to know in this context.

**Comment by mivalsten** [comment]
Well, following that logic, if you think that minecraft should have astral rituals then you should contact mojang about that, not mod developers.
The config is there to be modified, if you don't like it, change it. If modpack authors decide to use it, they will. If they decide that your input is valid and it should not generate netherite nor rock crystal then they will change it.
I have provided a solution that is working for me for the issue that I found, free of charge. I do not owe you anything, especially, I do not owe you any time spent or not spent on further dealing with this matter. You may take the solution, you may not, I do not care.

**Comment by VorpalLemur** [comment]
For comparison, the Botania Orechid is successfully able to generate other modpacks ores in this pack.   I know for a fact from experience that Mineralis in other modpacks has generated non-vanilla ores in the past.  This really looks like an oversight by the modpack devs and I personally hope to see it get resolved.

**Comment by mivalsten** [comment]
Given today's episode of Direwolf20's Let's Play, we can safely assume that this oversight will be fixed soon. :)
