### ISSUE TITLE
Regularly crashes (since v1.6.0) after a teleport  - java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by basneder** [FTBTeam/FTB-Presents-Direwolf20-1.16#207]
* **Modpack Version**: 1.6.1 
* **Issue**: 

When teleporting back to a certain location the client crashes fairly regularly, about 1 in 3. This happens when using a waystone or using the teleport of RFTools (using a porter).

The world where it happens was created with an older version of the pack and the crashing happened almost immediately after I upgraded to v1.6.1

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/70a3884d

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Don't know
* 
* **Known Fix**: No

**Comment by Sunekaer** [comment]
Issue this still an issue in 1.7.0?

**Comment by basneder** [comment]
I have not played much yet with the new version. But so far it seems not to crash.

**Comment by Sunekaer** [comment]
Awesome
