### ISSUE TITLE
v1.1 has huge memory leak

### ISSUE THREAD

**Issue by e30Birdy** [FTBTeam/FTB-Presents-Direwolf20-1.16#21]
I cannot tell you what the issue is and it is repeatable as 5 min in and the leak starts. I have tried all sorts of memory settings from 6 to 16gb dedicated and fills it right up. This is issue was never present on 1.0. Its not even screenshottable. Might be able to do a video on it if i screen capture instead of game capture but other users on dires twitter announcing the 1.1 update mentioned it as well. Game doesnt crash just locks up till it frees some memory, not really playable.

**Comment by capSAR273** [comment]
Also experiencing this. Does not seem to be affected by generating new chunks, the memory usage will creep higher until the game can't GC quick enough. Allocating more memory just delays how long before the freezes start.

**Comment by Sunekaer** [comment]
Hi 
We are looking into the issue

**Comment by DrunkTaank** [comment]
I disabled Create and it's KubeJS associated file and now the pack runs fine for me.

**Comment by ZeroNoRyouki** [comment]
Same problem here. I was able to grab a heap dump from my dying MC. Its full of vectors from Astral:

![heap](https://user-images.githubusercontent.com/7107662/102724473-08234900-4310-11eb-83fb-d2fc5da9abc2.PNG)

**Comment by capSAR273** [comment]
Removing Astral Sorcery from the pack fixed the issue for me. No leaking or freezes.

**Comment by Sunekaer** [comment]
> Same problem here. I was able to grab a heap dump from my dying MC. It is full of vectors from Astral by the look of it:
> 
> ![heap](https://user-images.githubusercontent.com/7107662/102724473-08234900-4310-11eb-83fb-d2fc5da9abc2.PNG)

Yes but even without AS the ram is still going up
![image](https://user-images.githubusercontent.com/18720460/102724921-49692800-4313-11eb-85ec-57b46c5c76e7.png)

**Comment by ZeroNoRyouki** [comment]
> > Same problem here. I was able to grab a heap dump from my dying MC. It is full of vectors from Astral by the look of it:
> > ![heap](https://user-images.githubusercontent.com/7107662/102724473-08234900-4310-11eb-83fb-d2fc5da9abc2.PNG)
> 
> Yes but even without AS the ram is still going up
> ![image](https://user-images.githubusercontent.com/18720460/102724921-49692800-4313-11eb-85ec-57b46c5c76e7.png)

I am testing it again, same config / world but no AS. Heap is stable and the GC is behaving itself

**Comment by Sunekaer** [comment]
yea i did a dump at join of world and now letting it run for like 40-60min and then see if i can see something

**Comment by capSAR273** [comment]
From leaving a game open for ~2 hours, no issues so far (With Astral Sorcery removed)

**Comment by Sunekaer** [comment]
Pushed 1.1.1 with a downgrade of AS

**Comment by tterrag1098** [comment]
That heap graph looks quite healthy. A sawtooth pattern at ~2/3 utilization is expected. You could probably lower the max heap. It would be nice to have a graph with AS installed to compare it against.

**Comment by JoJoDeveloping** [comment]
> Same problem here. I was able to grab a heap dump from my dying MC. It is full of vectors from Astral by the look of it:
> 
> ![heap](https://user-images.githubusercontent.com/7107662/102724473-08234900-4310-11eb-83fb-d2fc5da9abc2.PNG)

Out of interest (and in order to get such a diagram with AS installed), what tool did you use for this graph?

**Comment by capSAR273** [comment]
> 
> 
> > Same problem here. I was able to grab a heap dump from my dying MC. It is full of vectors from Astral by the look of it:
> > ![heap](https://user-images.githubusercontent.com/7107662/102724473-08234900-4310-11eb-83fb-d2fc5da9abc2.PNG)
> 
> Out of interest (and in order to get such a diagram with AS installed), what tool did you use for this heap dump visualization?

The tool used is called jmap

**Comment by HellFirePvP** [comment]
The issue lies in LinkedHashMap#removeEldestEntry not working properly, as seen here:
https://github.com/HellFirePvP/AstralSorcery/blob/a4b4bec48c22365af8330dfef241c48e48073696/src/main/java/hellfirepvp/astralsorcery/common/util/data/SizeLimitMap.java#L30
The map implementation has as feature the option to remove the eldest entry if that method returns true and is advertised to be used as such in its Javadoc, however doesn't work at random occasions it seems.
The implementation has changed for 1.13.8 in response to this.
