### ISSUE TITLE
Uncraftable jetpacks

### ISSUE THREAD

**Issue by charizard1596** [FTBTeam/FTB-Presents-Direwolf20-1.16#210]
* **Modpack Version**: Direwolf20 1.16

* **Issue**: Several Simply Jetpacks 2 jetpacks have no crafting recipe in JEI, and are uncraftable. These items include the Leadstone, Hardened, Reinforced, and Resonant jetpacks * 

* **Link to Log or Crash File Paste**: n/a
* **Is it Repeatable?**: Join world, and search "leadstone jetpack" in JEI. There will be no crafting recipe.
* **Mod/s Affected**: Simply Jetpacks 2
* **Known Fix**: n/a

**Comment by Sunekaer** [comment]
#77
