### ISSUE TITLE
Attempting to open chests and inventory doesn't open

### ISSUE THREAD

**Issue by Maudslay** [FTBTeam/FTB-Presents-Direwolf20-1.16#212]
![image](https://user-images.githubusercontent.com/21957751/107693035-7f88af80-6ca5-11eb-8e38-7cef52f0537c.png)

![4xodqc](https://user-images.githubusercontent.com/21957751/107695211-2ec68600-6ca8-11eb-9245-2875e985dcf5.gif)

* **Modpack Version**: FTB Presents Direwolf20 1.16 - 1.6.1

* **Issue**: Casually just playing this modpack with a friend all day no issues, the most recently thing I did/make was a coal coke oven from Immersive Engineering. Went off to do something else so I closed the server that is hosted on my pc. 3 hours later turned the server back on, I started to play again, went to open my chest full of ingot on top of my Redstone furnace and doesn't open. the error I get is above is from 2 different mods. I went to my other house and open chests (minecraft and iron chest) they open correctly).

* **Is it Repeatable?**: N/A, don't know how it occurs

* **Mod/s Affected**: Inventory Sorter and ldtteam (mine colony)

* **Known Fix**: Removing both mods fixes the issue but there are other bugs like below.

![Capture1](https://user-images.githubusercontent.com/21957751/107697350-08eeb080-6cab-11eb-979b-09a73d179856.PNG)

**Comment by Maudslay** [comment]
Just an update, put the mods back, put the map/world back that had the mods in it and it's working again. I'm assuming in start up something is causing these mods to block chests from being opened.

**Comment by SonicSpeedster16** [comment]
I had this happen to me once. Exiting out and reloading the game (client, not server) fixed it for me.

**Comment by Sunekaer** [comment]
The errors show has nothing to do with this issue, you'll see those even if you don't have the issue
1.16.4 is weird I have no way of replicating this issue so that I can debug it
But rejoin the world and the issue should be fixed
