### ISSUE TITLE
Reliquary Rare Items Not Dropping

### ISSUE THREAD

**Issue by nrllewellyn** [FTBTeam/FTB-Presents-Direwolf20-1.16#220]
* **Modpack Version**: 1.6.1

* **Issue**: Some rare mob loot items from Reliquary do not drop. Examples include: Eye of the Storm, Bat Wings, Squid Beaks, and Frozen Core. (Tested with 2 stacks of spawning eggs and a looting 3 diamond sword.) Also, none of the Reliquary items are present in the Woot loot tables.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 
reliquary-1.16.3-1.3.4.1061
woot-1.16.4-1.0.3.0

* **Known Fix**: N/A

**Comment by SonicSpeedster16** [comment]
Can't reproduce. I had a Squid Beak drop from a squid just last night. I also have several Bat wings and a Frozen Core in my Refined Storage System. I'm playing version 1.6.1 of the pack.

**Comment by nrllewellyn** [comment]
@SonicSpeedster16  Thanks for the feedback!

I just confirmed that this is an incompatibility with the "More Mob Heads" data pack from Vanilla Tweaks.

Sorry for the confusion, and thanks for your help! :-)
