### ISSUE TITLE
Crash Loop

### ISSUE THREAD

**Issue by memyselfandcj** [FTBTeam/FTB-Presents-Direwolf20-1.16#223]
So logged on to my server this morning and tried to access my Refined Storage and I kept getting booted from server. Restarted server and its now stuck in a crash loop.  

Version 1.6.1

Cannot get back on to recreate this issue.

Crash Log: https://paste.feed-the-beast.com/view/5b4ca128

**Comment by Sunekaer** [comment]
try and go to world\serverconfig\forge-server.toml and change removeErroringTileEntities  to true and start the server and see if that removes the block that crashes your server

**Comment by memyselfandcj** [comment]
Sorry should have closed this out. I have put a new pack on my server. Will do that now.
