### ISSUE TITLE
Infinite Cheese !

### ISSUE THREAD

**Issue by Tydesson** [FTBTeam/FTB-Presents-Direwolf20-1.16#224]
* **Modpack Version**: 1.6.1

* **Issue**: If you use a cyclic item user with a milk bucket inside, the cauldron is filled with milk but the bucket stays full inside the item user, allowing the cauldron to create cheese without using the milk bucket. Check screenshot for setup.

![cheese_for_days](https://user-images.githubusercontent.com/3941898/109417916-e3111d80-79c5-11eb-8068-5af7ad68924b.png)

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Cyclic / Rats

**Comment by Sunekaer** [comment]
https://github.com/Lothrazar/Cyclic/issues/1777

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
