### ISSUE TITLE
[Suggestion] Add BlockDrops

### ISSUE THREAD

**Issue by OneLemonyBoi** [FTBTeam/FTB-Presents-Direwolf20-1.16#227]
BlockDrops is a QoL mod that makes it easier to see what items different blocks drop. It also shows what the rate of drops are for different types of Fortune. This mod shows all blocks that change when broken, like grass and stone, as well as ores, like coal and emerald.

ModPage: [https://www.curseforge.com/minecraft/mc-mods/blockdrops](https://www.curseforge.com/minecraft/mc-mods/blockdrops)

**Comment by Sunekaer** [comment]
Wont be added
