### ISSUE TITLE
Internal Server Error - Storage Bag (Cyclic) - Pickup Mode: Everything

### ISSUE THREAD

**Issue by EasyThe** [FTBTeam/FTB-Presents-Direwolf20-1.16#234]
* **Modpack Version**: 1.7.0

* **Issue**: Internal Server Error - kicking the player from the server

**Steps to reproduce:**
1. Craft/Get **Storage Bag** from **Cyclic**
2. Open the bag and set **Pickup Mode** to **Everything**
3. Try to pick up an item from the ground.
4. Observe

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/84c21720

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Cyclic 1.16.5-1.1.8

**Comment by Sunekaer** [comment]
https://github.com/Lothrazar/Cyclic/issues/1775
