### ISSUE TITLE
Eviro Core Interconnects have no recipe on MP server

### ISSUE THREAD

**Issue by zrieprakis** [FTBTeam/FTB-Presents-Direwolf20-1.16#236]
Running standard, unmodified server and client packs. Machines have 96GB and 32GB mem, respectively.

Modpack Version:
1.7.0

Issue:
JEI doesn't display recipes when clicked on a client connected to a dedicated MP server. The same client will display the recipe when running SP.

Link to Log or Crash File Paste:
Can provide links to client and server card if needed.

Is it Repeatable?:
Yes.

Mod/s Affected:
Environmental Core / Environmental Tech

Known Fix:
Not a "fix," but issue doesn't occur on SP sessions.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by zrieprakis** [comment]
Apologies- Post edited and same post copied here.

Running standard, unmodified server and client packs. Machines have 96GB and 32GB mem, respectively.

Modpack Version:
1.7.0

Issue:
JEI doesn't display recipes when clicked on a client connected to a dedicated MP server.  The same client will display the recipe when running SP.

Link to Log or Crash File Paste:
Can provide links to client and server card if needed.

Is it Repeatable?:
Yes.

Mod/s Affected:
Environmental Core / Environmental Tech

Known Fix:
Not a "fix," but issue doesn't occur on SP sessions.

**Comment by zrieprakis** [comment]
> issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

Apologies- Post edited and same post copied here.

Running standard, unmodified server and client packs. Machines have 96GB and 32GB mem, respectively.

Modpack Version:
1.7.0

Issue:
JEI doesn't display recipes when clicked on a client connected to a dedicated MP server. The same client will display the recipe when running SP.

Link to Log or Crash File Paste:
Can provide links to client and server card if needed.

Is it Repeatable?:
Yes.

Mod/s Affected:
Environmental Core / Environmental Tech

Known Fix:
Not a "fix," but issue doesn't occur on SP sessions.

**Comment by Snappiestjack** [comment]
Any update on this?

**Comment by Sunekaer** [comment]
The recipes are they
just not showing in JEI
Mod dev is aware

**Comment by Snappiestjack** [comment]
So .... after loading up single player to screen shot all the assembly recipes, I loaded back into my server and the recipes now show.

**Comment by zrieprakis** [comment]
> The recipes are they
> just not showing in JEI
> Mod dev is aware

Thanks - could the tag be changed from "awaiting reply" to "open?"

**Comment by zrieprakis** [comment]
> So .... after loading up single player to screen shot all the assembly recipes, I loaded back into my server and the recipes now show.

Interesting.  That would denote a client issue.  I'll try wiping my client instance & see what happens.

**Comment by zrieprakis** [comment]
So I've done a little testing...

Wiped and reinstalled client instance.  Connected to server, same problem.
Wiped server instance.  Redownloaded server.  Recipes visible.
Moved current world to new server.  Recipes visible.
Changed server settings to my preferred and opped myself.  Recipes still visible.

Not sure WTH was wrong, but I follow that same procedure for every upgrade.  This was just the second time I've done it.  That shouldn't have worked.  Oh, well.  If Val actually spotted a bug, that's amazing.  Thanks for the review!
