### ISSUE TITLE
undergarden diamond ore breaks orechid/weight lens 

### ISSUE THREAD

**Issue by Paperweight82** [FTBTeam/FTB-Presents-Direwolf20-1.16#238]
* **Modpack Version**: 1.7.0

* **Issue**: the diamond ore from the undergarden is not affected by botania's weight lens, so breaks a farm using this method of ore collection. while there are easy (though not perfect) workarounds (bore lens works but results in lower resource yield for all ores) i don't think it's really compatible with the orechid flower for this reason, and i think it should be removed from the flower's list of ores.
* i think it's ore-dictionaried as diamond ore, which is why the flower generates it? but i don't consider them to be equivalent for the reason above.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes, every undergarden diamond ore will generate but not fall when struck with "weight" mana pulse

* **Mod/s Affected**: botania, the undergarden

* **Known Fix**: remove undergarden diamond ore from orechid or don't oredic them as the same?

**Comment by Sunekaer** [comment]
The issue is there is no way to remove or change the weight of ores from what I can see, I have only found a way of adding ores.
Please report to Botania

**Comment by Paperweight82** [comment]
ok, thanks for the fast reply! i already reported it to undergarden mod and they knew nothing about it... i think it is sort of an obsidian block with diamond in it, essentially, so behaves the same as vanilla obsid for botania.
can the ore dictionary entry for the ore not be changed so they arent viewed as interchangable? (not meaning to ask the same thing twice, i just have no idea how to do that, if it can even be done at all?)

**Comment by Paperweight82** [comment]
so it looks like this is actually in the process of being fixed
https://github.com/Vazkii/Botania/issues/3667
https://www.reddit.com/r/botania/comments/m4gepp/orechid_config_is_it_a_thing/
