### ISSUE TITLE
Tetra Geodes give multiple variants of metal nuggets

### ISSUE THREAD

**Issue by AwesmePersn** [FTBTeam/FTB-Presents-Direwolf20-1.16#239]
* **Modpack Version**: 1.7.0

* **Issue**: Tetra Geodes giving multiple variants of nuggets.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tetra

Opening Tetra geodes can yield multiple variants of copper nuggets as an example. I believe this applies for all modded metals that it can give you.

Everything else I've encountered so far has only given me one variant of each metal.

To reproduce, grab a Tetra hammer and workbench. Put the geodes in the workbench and open a bunch. You will end up with multiple variants of each modded metal nugget you get.

**Comment by Sunekaer** [comment]
Hi, 

Could you test with the newest version there just was released?
