### ISSUE TITLE
Infinite Ingot Dupe

### ISSUE THREAD

**Issue by phit** [FTBTeam/FTB-Presents-Direwolf20-1.16#24]
* **Modpack Version**:  1.1.1

* **Issue**: https://www.youtube.com/watch?v=r_tZLg5z3zo
  you can't treat all dust like Create dust, it allows players to dupe any ingot

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yup

* **Mod/s Affected**: any dust you changed to the processable by Create

* **Known Fix**: don't treat all modded dusts like Create dusts

**Comment by Sunekaer** [comment]
fix pushed

**Comment by phit** [comment]
thank you!
