### ISSUE TITLE
Mana and Artifice - Greater Ring of Breaking not functional

### ISSUE THREAD

**Issue by Kezarious** [FTBTeam/FTB-Presents-Direwolf20-1.16#242]
* **Modpack Version**: 1.7.0

* **Issue**: Ring of breaking(greater) from Mana and Artifice doesn't work with my simple break+touch spell (No added components. With it equipped in my baubles slot, or even in my inventory, it doesn't increase the breaking power of my spell and i'm unable to mine diamond ore, where I should theoretically be able to mine up to obsidian. I notice no difference when mining different blocks whether I have the ring on me or not.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mana and Artifice

**Comment by Sunekaer** [comment]
Hi, 

Could you test with the newest version there just was released?
