### ISSUE TITLE
Create farms and Psi overgrowth

### ISSUE THREAD

**Issue by Icemanap** [FTBTeam/FTB-Presents-Direwolf20-1.16#243]
Direwolf20 1.16.5, versions 1.6-1.7
For unkown reasons, my game crashes and the map file gets corrupted (i guess, not an it person, so i am not aware of the correct terminology) whenever I use the Psi overgrowth spell on my Create wheat farm. Specifically, when I try to load my single player world it reads world data, but gets stuck at 100% when loading the world  The farm is a minecart with the harvesters that just travels in a closed circuit around farmland. This bug is repeatable.  This is the output of the game when the crash happens:
12:39:32.619 game [12:39:32] [Server thread/INFO] [minecolonies/]: Finished discovering saplings
12:39:33.041 game[ 12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering Ores
12:39:33.052 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering compostables
12:39:33.112 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering plantables
12:39:33.112 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering lucky oreBlocks
12:39:33.114 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering recruitment costs
12:39:33.117 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering diseases
12:39:33.119 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished initiating sifter config
12:39:33.138 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering food
12:39:33.223 game [12:39:33] [Server thread/INFO] [minecolonies/]: Finished discovering fuel
12:39:33.336 game [12:39:33] [Server thread/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_custom_voxel_collision' ASM patch...
12:39:33.355 game [12:39:33] [Server thread/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_custom_voxel_collision' ASM patch!
12:39:33.359 game [12:39:33] [Server thread/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Adding 'add_custom_collision_flag' ASM patch...
12:39:33.376 game [12:39:33] [Server thread/INFO] [ne.mi.co.Co.astralsorcery/COREMODLOG]: Added 'add_custom_collision_flag' ASM patch!
12:39:33.479 game [12:39:33] [Server thread/INFO] [ObserverLib/]: Load CachedWorldData 'lightnetwork' for world minecraft:eek:verworld
12:39:33.507 game [12:39:33] [Server thread/INFO] [ObserverLib/]: Loading of 'lightnetwork' for world minecraft:overworld finished.
12:39:33.526 game [12:39:33] [Server thread/INFO] [pneumaticcraft/]: Rebuilding Amadron offer list
12:39:33.551 game [12:39:33] [Server thread/INFO] [pneumaticcraft/]: 30 active Amadron offers to sync to clients
12:39:34.800 game [12:39:34] [Server thread/INFO] [minecraft/IntegratedServer]: Changing view distance to 9, from 10
12:39:34.860 game [12:39:34] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 4269ms or 85 ticks behind
12:39:34.975 game [12:39:34] [Server thread/WARN] [Mekanism/]: Failed to retrieve username for UUID 98df46f8-32ec-43a6-8b12-5bc815fb4d45, you might want to add it to the JSON cache
12:39:36.910 game [12:39:36] [Netty Server IO #1/INFO] [co.li.co.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.
12:42:59.273 game [12:42:59] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@3b414a1b
12:44:43.659 game [12:44:43] [Render thread/INFO] [Astral Sorcery/]: Built PerkTree with 417 perks!

And after this it got stuck for 20 mins and i decided to close the game. This exact output is repeated every time i load the world.

**Comment by Sunekaer** [comment]
Hi, 
Do you have any crash report or debug log?
There is not a lot of information here to go off
