### ISSUE TITLE
Duping Refined Storage Speed Upgrades when Sorting Crafter's Inventory.

### ISSUE THREAD

**Issue by SotomaniaGr** [FTBTeam/FTB-Presents-Direwolf20-1.16#244]
Modpack Version: 1.7.0

Issue: When Sorting the Inventory of any Refined Storage Crafter (even the N,D,G,I variations) that has at least one speed upgrade on,  it replaces the first pattern with a speed upgrade which can be used normally.
After discovering that, I tested other machines that may be affected in some way when sorted. Found out that Sorting Powah Reactors makes the Redstone and Ice disappear from their slots. (as if they got voided), there may be other mods affected by this as well.

Is it Repeatable?: Yes

Mod/s Affected: Simple Inventory Sorter, Refined Storage, Powah and potentially more.

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/101
