### ISSUE TITLE
RFTools Dimensions Researcher Crash

### ISSUE THREAD

**Issue by crwoody** [FTBTeam/FTB-Presents-Direwolf20-1.16#245]
* **Modpack Version**: DW20 1.16 v1.70 / rftoolsdim v1.16-7.04

* **Issue**: Placing unknown dimlet in researcher causes crash

* **Known Fix**: https://github.com/McJtyMods/RFToolsDimensions/issues/330 Issue has been fixed rftools needs updated.

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
