### ISSUE TITLE
Impossible to determine which major version of a client is installed

### ISSUE THREAD

**Issue by gzcwnk** [FTBTeam/FTB-Presents-Direwolf20-1.16#246]
* **Modpack Version**: If I knew I wouldnt be asking

* **Issue**: Impossible to easily determine which modpack version is in use.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: no idea

* **Known Fix**: write some code to ID exact verision number easily.

**Comment by krustymk** [comment]
All the info is on the start screen, 1.16 top right, forge bottom right.

**Comment by gzcwnk** [comment]
No it isnt.   If you look at the server files you can see a patch number,

serverinstall_79_218

I tried 6 different server sets and only 218 and 217 worked but 218 lost items, 219+ wouldnt let me in.

So I need to know the client patch number also in order to be compatible.  
I have tried to update the client and that just crashes on newer clients so there is an issue there somewhere also

**Comment by gzcwnk** [comment]
Hmm looks like its the FTB launcher has an issue I can run direwolf20 1.162 perfectly fine in MultiMC5.

**Comment by Sunekaer** [comment]
All this information is not something i can provide in the game as its generated by another system when the pack is released, you are able to see the information on our website.
