### ISSUE TITLE
After upgrading to 1.16-6 mining world is no longer available I get a 

### ISSUE THREAD

**Issue by gzcwnk** [FTBTeam/FTB-Presents-Direwolf20-1.16#248]
* **Modpack Version**: 1.165- 224?  

* **Issue**: no longer able to access mining world

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: After original block did nt work I created a new block, same error

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/188
