### ISSUE TITLE
Mob Duplicator not working (Industrial Foregoing)

### ISSUE THREAD

**Issue by mpengle** [FTBTeam/FTB-Presents-Direwolf20-1.16#249]
* **Modpack Version**: 
1.7.0

* **Issue**: 
When using the mob duplicator it will not function due to not detecting the required mob is in the slot.  This has been fixed in the latest version.

* **Link to Log or Crash File Paste**: 
No crash

* **Is it Repeatable?**: 
Yes, the mob duplicator is not working according to the patch notes for industrial foregoing

* **Mod/s Affected**: 
Industrial Foregoing

* **Known Fix**: 
Update to 3.2.11 
"Fixed Mob Duplicator not checking if there was an entity in the MIB, closes #1055 (by Buuz135) [e6591ef1018ed43]"

**Comment by Snappiestjack** [comment]
I'd love to get IF updated too. I have mob duplicators ready to go on my server, it would be a hassle to get everyone to manually update on mod. Dire needs to try to use the mob duplicator so he finds out it doesn't work.
