### ISSUE TITLE
Fluxbore can only mine single block

### ISSUE THREAD

**Issue by rolsch8026** [FTBTeam/FTB-Presents-Direwolf20-1.16#254]
* **Modpack Version**:  Direwolf20 1.16 ver. 1.8.0
* 
*  **Issue**: After update Fluxbore only mined a single block.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  unknown

* **Mod/s Affected**: 

* **Known Fix**: I put the Fluxbore into the Tinker's Workbench. I removed its augments. I reinstalled its augments. The Fluxbore worked correctly.

**Comment by Sunekaer** [comment]
Okay thanks for the information
