### ISSUE TITLE
DW20 Server will not start with minecolonies/structurize

### ISSUE THREAD

**Issue by kernelstubbs** [FTBTeam/FTB-Presents-Direwolf20-1.16#256]
* **Modpack Version**: 1.8 and 1.9

* **Issue**: Server fails to start - crashes loading minecolonies JAR

* **Link to Log or Crash File Paste**: https://pastebin.com/qEZ3s23U
* **Is it Repeatable?**: Yes
* **Mod/s Affected**: structurize/minecolonies

* **Known Fix**: update structurize/minecolonies to latest ALPHA

**Comment by trentech** [comment]
Same issue here.

**Comment by jsmith0012** [comment]
Also same issue.  And dose anyone know the best version of Java to use?   Currently using openjdk 11

**Comment by Mekanofreak** [comment]
Same Here, single player works, server crash when loading, both on window and Ubuntu

**Comment by Sunekaer** [comment]
Use java 8

**Comment by Mekanofreak** [comment]
using java 8 update 281 on my windows system, still got the same crash

**Comment by Sunekaer** [comment]
logs?..

**Comment by Mekanofreak** [comment]
I read the logs, it say It's using java 11 but It doesn't show up as installed on the system and the java info panel says java 8. Dunno how that happened, will clean java out and try with a java 8 fresh install.

**Comment by Mekanofreak** [comment]
Found the culprit, sems like another application installed AdoptOpenJDK on my system as a requirment. Anyone that got the same issue but only see java 8 installed maybe check for it.
