### ISSUE TITLE
structurize:0.13.163-ALPHA causing ubuntu server install to Crash (clean install)

### ISSUE THREAD

**Issue by pears0** [FTBTeam/FTB-Presents-Direwolf20-1.16#258]
* **Modpack Version**: 1.9.0

* **Issue**: Fresh ubuntu 20.04 server install, correctly ran the server install script, tried to launch server with start.sh and server is crashing when trying to load Structurize

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/051df204

* **Is it Repeatable?**: Yes, I get the same error each time I try to start the server.

* **Mod/s Affected**: structurize:0.13.163-ALPHA

* **Known Fix**: Nope, sorry

**Comment by SonicSpeedster16** [comment]
You must use Java 8 or it will crash.

Duplicate of #256

**Comment by pears0** [comment]
Yes, I've just seen that is seems Ubuntu 20.04 and up is now installing java 11 by default and I'd not realised.
