### ISSUE TITLE
Pack is world genning all immersive ores and isnt genning any thermal ores. 

### ISSUE THREAD

**Issue by NotKais** [FTBTeam/FTB-Presents-Direwolf20-1.16#26]
Missing a few ores

**Comment by MacChuck** [comment]
I just tested a 1.1.1 fresh survival world with a cheated in digital miner and was able to pull up all of the Thermal ores in a 32 block radius.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed
