### ISSUE TITLE
World not loading on latest version

### ISSUE THREAD

**Issue by Commandore32** [FTBTeam/FTB-Presents-Direwolf20-1.16#277]
* **Modpack Version**: 

1.11.1

***Issue**: 

World not loading on the latest version. My creative test world loads and works perfectly, but my regular world doesn't load at all. it just says reading world data, the words disappear, and it gets stuck. I didn't have this issue in 1.10.1
 
* **Link to Log or Crash File Paste**: 
(The folder below contains the world saves and the logs)
 
https://drive.google.com/drive/folders/1DNSH0c31BdEH9WJTr1PmqY0czqFT7o6N?usp=sharing

I'm not

* **Is it Repeatable?**: 
Every time I try to load my main world, it doesn't work 
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Commandore32** [comment]
Sorry, the modpack version is 1.11.0 .

**Comment by CanusLupus** [comment]
Hi,

looks like the **immersiveengineering-server.toml** file in the **New World/serverconfig/** folder is corrupt but the version in the **New World (1)/serverconfig/** folder is fine. You can copy it over and try again.

I hope that will help :)

**Comment by Commandore32** [comment]
What I had to do: I deleted the immersive engineering-server.toml and thermal-server.toml files and it worked! Canus saw that they failed to load in the log files.

**Comment by Commandore32** [comment]
The log files only show one corrupt file at a time. Delete one and it will show the next one during the next reload.
