### ISSUE TITLE
Refined Storage right-click use not working

### ISSUE THREAD

**Issue by camcam95** [FTBTeam/FTB-Presents-Direwolf20-1.16#28]
* **Modpack Version**: 1.1.2

* **Issue**: Can no longer access the grid nor crafting grid to view items in system

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/263f08e5

* **Is it Repeatable?**: Unknown

* **Mod/s Affected**: Refined Storage

* **Known Fix**: Unknown

**Comment by camcam95** [comment]
Note, the other Refined Storage blocks are still accessible. Also, all other processes on the server are still moving/working.

**Comment by Sunekaer** [comment]
Server or SP?
Claimed area, claimed by you or another, are you allied?
