### ISSUE TITLE
Stutters in Creative World

### ISSUE THREAD

**Issue by 923penguin** [FTBTeam/FTB-Presents-Direwolf20-1.16#29]
Whenever I play in my creative world, I get regular stutters like in the 1.1.0 release with Astral Sorcery. This is a superflat world made for testing stuff in creative; I don't have this problem in my regular, normal gen world.

**Comment by camcam95** [comment]
You need to upgrade to 1.1.1 at least. Astral sorcery is buggy and causes memory leaks in 1.1.0

**Comment by 923penguin** [comment]
I am in 1.1.2. Like I said, normal worlds don't have the problem. When I make a superflat world it starts happening.

**Comment by camcam95** [comment]
Press f3. How many entities are alive?

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed
