### ISSUE TITLE
Can't hide/disable minetogether

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Presents-Direwolf20-1.16#3]
Modpack Version: 1.0

Issue: Minetogether X button in multiplayer menu isn't clickable, no mod options to disable it.

Link to Log or Crash File Paste: n/a

Is it Repeatable?: Yes

Mod/s Affected: minetogether

**Comment by Sunekaer** [comment]
https://github.com/CreeperHost/MineTogether/issues/421
