### ISSUE TITLE
Mob Crusher getting stupid amount of skeleton drops

### ISSUE THREAD

**Issue by sunkenvelius** [FTBTeam/FTB-Presents-Direwolf20-1.16#31]
Modpack Version: Direwolf 20 1.16.4 update 1.1.1 

Issue: Mob Crusher is generating a ridiculous amount of skeleton drops and not killing other mobs. When I take out the range upgrade, I have a tier 12 in now, it does not spawn skeletons in my dark room. When it is in I do not get skeletons on my mini map not like the machine is killing. I have tried multiple upgrade levels it seems to continuously spawn and kill skeletons without spawning them in the world. There is no extra spawn techniques except dark room. 

Link to Log or Crash File Paste:

Is it Repeatable?: Yes

Mod/s Affected: Industrial foregoing

**Comment by Sunekaer** [comment]
I'm not able to recreate this issue.
are you on a server?
Claimed area?
If claimed: 
  Is it claimed by you or another?
  Are you allied?
  Have you allied Industrial foregoing?
