### ISSUE TITLE
crash with cyclic bag

### ISSUE THREAD

**Issue by LWmods** [FTBTeam/FTB-Presents-Direwolf20-1.16#33]
-->

* **Modpack Version**: 1.1.2

* **Issue**: server closed apon hitting one of the buttons in the cyclic bag

* **Link to Log or Crash File Paste**: https://pastebin.com/uk3QzJQP

* **Is it Repeatable?**: yes

* **Mod/s Affected**: cyclic

* **Known Fix**: none

**Comment by Sunekaer** [comment]
Please test with 1.2.0 and let me know if it's still an issue
