### ISSUE TITLE
[FIXED] Game freezes when on a server. Either after 2 min or after an hour.

### ISSUE THREAD

**Issue by Luk3-V** [FTBTeam/FTB-Presents-Direwolf20-1.16#35]
Hi, I am currently playing on a server & whenever I connect for the first time my game freezes after 2 minutes BUT then is fine for another hour or so. After an hour I freeze again & disconnect. Then whenever I rejoin & freeze after 2 minutes I always disconnect.

I can run FTB Revelation just fine though & it has way more mods.

I've tried allocating less & more ram, I've tried reinstalling java, reinstalling the modpack. Allocating different amount of RAM seems to change how often the freezing occurs. The freezing also doesn't seem to happen on single player worlds.

I have 6gb out of 8gb of RAM allocated. Java 1.8.0_271.

Modpack Version: 1.1.2

* **Issue**: Game freezing & disconnecting when on server

* **Link to Log or Crash File Paste**: 
Logs after first disconnect:  https://pastebin.com/kQFgAbqd
Logs after rejoining & disconnecting:  https://pastebin.com/eh5Jz2rW

* **Is it Repeatable?**: Yes

**Comment by Luk3-V** [comment]
Using these Java arguments seems to fix the memory problem.

`-XX:+UseG1GC -Xmx6G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by Sunekaer** [comment]
Pinned so others can find and use these

**Comment by UndarkAido** [comment]
> Using these Java arguments seems to fix the memory problem.
> 
> `-XX:+UseG1GC -Xmx6G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

Did you add the arguments to the server or to the client?

**Comment by Luk3-V** [comment]
> > Using these Java arguments seems to fix the memory problem.
> > `-XX:+UseG1GC -Xmx6G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
> 
> Did you add the arguments to the server or to the client?

@UndarkAido I put it in the client arguments using the FTB Launcher.
