### ISSUE TITLE
Placing Immersive Engineering waterwheel "from above" facing down towards block face *only works when facing east and west*

### ISSUE THREAD

**Issue by Cazadorro** [FTBTeam/FTB-Presents-Direwolf20-1.16#36]
* **Modpack Version**:  1.1.2

* **Issue**: If you try to place a water wheel on the north or south face of a block, while standing on top of said block, it is impossible.  This means only east/west configurations of adjacent full waterwheel sets are possible. 

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: persists after reload

* **Mod/s Affected**: Immersive engineering

* **Known Fix**: use east and south facing 6 wheel 2 kinetic dynamo structures.  Not really a fix

**Comment by Sunekaer** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4538

**Comment by Cazadorro** [comment]
fixed in https://github.com/BluSunrize/ImmersiveEngineering/commit/17da6b0c721703587e8b6a937684c56c0f550447
