### ISSUE TITLE
Error details: The operation completed successfully.

### ISSUE THREAD

**Issue by Mannyita** [FTBTeam/FTB-Presents-Direwolf20-1.16#37]
Filename on disk: 1.0.17
Path: C:\Users\emman\AppData\Local\Overwolf\Extensions\cmogmmciplgmocnhikmphehmeecmpaggknkjlbag\1.0.17
Exists: Nonexistent

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed
