### ISSUE TITLE
Sound Muffler button causes crash in Open to LAN mode.

### ISSUE THREAD

**Issue by Shadowfire86** [FTBTeam/FTB-Presents-Direwolf20-1.16#38]
* **Modpack Version**: 1.1.2

* **Issue**: Clicking the sound muffler button on your inventory menu causes a singleplayer/Open to LAN mode crash

* **Link to Log or Crash File Paste**: Currently missing, will edit with new one soon.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Sound Muffler mod, last version of 1.1.2 pack.

* **Known Fix**: Don't use the Sound Muffler

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by Shadowfire86** [comment]
Please post a copy of the template? When posting this issue I was not given one.

**Comment by Shadowfire86** [comment]
appears fixed in 1.2 version of pack or on server.
