### ISSUE TITLE
Memory Leak in 1.1.2

### ISSUE THREAD

**Issue by john01dav** [FTBTeam/FTB-Presents-Direwolf20-1.16#39]
* **Modpack Version**: 1.1.2

* **Issue**: Within an hour or so, my server's memory fills up to the point that GC strain tanks the TPS. It never seems to crash.

* **Link to Log or Crash File Paste**: Nothing special is i nthe logs

* **Is it Repeatable?**: It happens to my server reliably after just under an hour. 

* **Mod/s Affected**: Unknown

* **Known Fix**: Right now, we're doing automated restarts every hour along with ZGC on Java 14 to try to control the lag, but this isn't a real solution — just a stopgap measure to reduce the impact. 

I'm working on some heap analysis to figure out what code is at fault, but I do not have any information to report from this yet.

**Comment by Sunekaer** [comment]
Have you tried using any java args?
Have you profiled the server that isnt just mobs or items causing the lag?
How much ram you giving the server?

**Comment by john01dav** [comment]
I used my standard Java arguments that every server that I host uses, and
it didn't help. I switched to Java 14 and enabled ZGC with 16 GC threads,
which pinned every thread and improved TPS supporting that it's a memory
leak where the heap fills up. A restart, even if everyone rejoins after it
removes the lag until it comes back a bit under an hour later, so excessive
entities is unlikely to be the culprit. The server has 8GBs of maximum
allocation (Xmx).

It looks like the culprit is Create. The issue didn't occur at all in
1.1.0, and when players reduced the amount of Create that they're using the
issue's severity lessened.

**Comment by Sunekaer** [comment]
Sorry for the late reply.
Hmm 16 GC threads sound like a lot, do you also have this in 1.2.0?

**Comment by john01dav** [comment]
> Sorry for the late reply.
> Hmm 16 GC threads sound like a lot, do you also have this in 1.2.0?

The issue persists in 1.2.0. We can barely control it with hourly restarts.

**Comment by Sunekaer** [comment]
Sounds really weird, im not sure whats causing the issue.
i cant recreate the issue to the level that you have it

**Comment by john01dav** [comment]
> Sounds really weird, im not sure whats causing the issue.
> i cant recreate the issue to the level that you have it

It looks like Create is, since it started after the update that added it (we launched 1.0.0 initially, and the issue wasn't present). My server is lucky enough to be quite popular (it's plausible that there are more than 50 different players' create setups chunk loaded), so this is likely why you can't recreate the issue.

**Comment by Sunekaer** [comment]
A lot other mods got updated dated in that update, and we have been running create for months on other servers without issues

**Comment by john01dav** [comment]
> A lot other mods got updated dated in that update, and we have been running create for months on other servers without issues

Have you had a similar number of active bases? If so, then it's probably something else (although varying setups are still a possibility). If it's not Create, then I don't know what it is.

**Comment by Sunekaer** [comment]
Could you check how it goes with 1.3.1?
