### ISSUE TITLE
Rendering Issue after looking at the emote menu

### ISSUE THREAD

**Issue by xellosmetallum** [FTBTeam/FTB-Presents-Direwolf20-1.16#4]
* **Modpack Version**: Direwolf20 for 1.16 version 1.0.0

* **Issue**: When browsing through the emotes that are available in chat it causes the entire world render to take off all textures and show pink blank blocks. This includes torches and other items as well.

* **Link to Log or Crash File Paste**: No crash caused. Links to Screenshots: [https://imgur.com/a/O1xqIz6](https://imgur.com/a/O1xqIz6) [https://imgur.com/a/ZdtxasN](https://imgur.com/a/ZdtxasN)

* **Is it Repeatable?**: Yes I can repeat this consistently by going into the emote menu in chat.

* **Mod/s Affected**: Emojiful 1.15.3 v 2.1.1

* **Known Fix**: Restarting the entire modpack.

**Comment by Sunekaer** [comment]
Do you have a log of the game from when this happened?

**Comment by xellosmetallum** [comment]
Here is the log paste https://paste.feed-the-beast.com/view/24c8ae80

**Comment by Sunekaer** [comment]
Have you change texture pack or any graphics settings?

**Comment by Sunekaer** [comment]
Also how much ram do you have allocated to the pack?

**Comment by xellosmetallum** [comment]
6G of ram and default texture pack.

**Comment by Sunekaer** [comment]
Every weird as its complaining about "Failed to load texture: minecraft:textures/atlas/blocks.png"
Could you try install another instance of the pack and see if it also happens there

**Comment by xellosmetallum** [comment]
Ok on a new instance of the pack I cannot get it to repeat that weird error.

**Comment by Sunekaer** [comment]
Okay thanks, there must have gone something wrong with the installation of vanilla in the other instance.
Have fun and let us know if you have other issues :)
