### ISSUE TITLE
Server crashed when getting close to a skeleton horse

### ISSUE THREAD

**Issue by dennisblokland** [FTBTeam/FTB-Presents-Direwolf20-1.16#40]
* **Modpack Version**:  1.1.2

* **Issue**:  Server crashed when getting close to a skeleton horse

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1f0f8220

* **Is it Repeatable?**:  No, when i spawn in a skeleton horse the same thing doesnt happen

* **Mod/s Affected**:  i think it has something to do with

**Comment by Sunekaer** [comment]
Full crash log?

**Comment by dennisblokland** [comment]
https://paste.feed-the-beast.com/view/raw/edbb83b0

**Comment by malte0811** [comment]
See also https://github.com/MinecraftForge/MinecraftForge/pull/7509. It's easy to fix with a Mixin for now, I made one for ForgeCraft after the second skeleton horse trap.
