### ISSUE TITLE
Game crash Sound engine/ERROR minecraft/ALUtils: unable to allocate memory

### ISSUE THREAD

**Issue by draav** [FTBTeam/FTB-Presents-Direwolf20-1.16#43]
* **Modpack Version**: Direwolf 20 1.1.2

* **Issue**: I was in a nether fortress killing a blaze with a tetra sword. The game crashed with the error message 

    ```[17:41:00] [Sound engine/ERROR] [minecraft/ALUtils]: Assigning buffer data: Unable to allocate memory.```

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3684cfcc

* **Is it Repeatable?**: no

**Comment by Sunekaer** [comment]
How much ram you giving the pack?

**Comment by draav** [comment]
6 GB

**Comment by Sunekaer** [comment]
Could do try with more assigned?

**Comment by draav** [comment]
I haven't been able to reproduce this crash specifically. However my computer only has 8gb, i can't assign it anymore safely.

**Comment by Sunekaer** [comment]
Then the only thing i can say is try and run with args like https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/35
