### ISSUE TITLE
Can't start woot mod in direwolf20 1.16.4 v 1.1.2 because heads don't drop

### ISSUE THREAD

**Issue by Shadowfire86** [FTBTeam/FTB-Presents-Direwolf20-1.16#46]
* **Modpack Version**: 1.1.2

* **Issue**: Monster heads (other than Wither Skeletons) don't drop from kills. This makes woot extremely difficult to get started (Factory Heart requires 4 heads/skulls) with and makes the head perk uncraftable.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: woot

* **Known Fix**: cheat in the required heads for the head perk, loooooong farm to even start.

**Comment by Sunekaer** [comment]
I just tested in my world with a sword there has looting 3 on it and I got 1 head from killing 38 wither skeletons

**Comment by Sunekaer** [comment]
Could you do some creative testing with looting 3 because i cant recreate this issue

**Comment by willrun4fun** [comment]
I have Beheading III on my sword and I am drowning in heads.  Piles of them.

**Comment by Shadowfire86** [comment]
I didn't have Beheading. To get started I finally went hunting for Wither Skeleton heads, but yeah I guess beheading would be the only way to get Zombie and regular skeleton heads. Previous versions the heads had a drop chance from their respective mods (Direwolf20 1.12 MC I think was the last). I guess the Beheading thing works around to making them drop.

**Comment by robertm1771** [comment]
Mob farm ran for 12 hours with no skulls using dark utils player damage  for kills. Got lucky and found beading 3 sword to get start in woot

**Comment by willrun4fun** [comment]
Yeah, beheading 3 sword I get sometimes 3 skulls from one wither skeleton.

**Comment by JustLiam040** [comment]
As a temporary workaround people can use botania, you can create vazkii's head in a apothecary using 16 pink petals, these work with the woot head recipes :)

**Comment by Shadowfire86** [comment]
Workarounds noted. Thinking of leaving this up for informational purposes? If not please feel free to close the issue.
