### ISSUE TITLE
Stuck when loading the pack

### ISSUE THREAD

**Issue by Ash6390** [FTBTeam/FTB-Presents-Direwolf20-1.16#49]
- **Modpack Version**: 1.1.2
- **Issue**: Can't load the pack at all. Gets stuck on "Atlas Stitching", even with up to 7GB of RAM allocated (usage goes up to 30% at most while loading, then settles to around 20%).
- **Is it repeatable?**: on my PC? Yes, happens every time.
- **Known fix**: none as of yet.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by willrun4fun** [comment]
Mine won't even get past the Minecraft Launcher.  Fails with exit code 0 immidiately.  I rolled back for now.

**Comment by Xjack998** [comment]
I have the same issue, is there any fix? I tried to reinstall the app and the Pack, but nothing changed
