### ISSUE TITLE
Can't change resourcepack

### ISSUE THREAD

**Issue by kd0pls** [FTBTeam/FTB-Presents-Direwolf20-1.16#5]
Tried Soartex and Invictus and they either crash straight away or attempt to revert then crash.  8GB RAM and CPW java arguments used.

**Comment by Sunekaer** [comment]
More information needed, please fill out hte template

**Comment by capSAR273** [comment]
I've had the same issue, the error I keep seeing is `Tag forge:creosote used before it was bound`, gets output many times during the crash. I do have optifine installed but that is the only deviation I have from the standard pack. I've tried putting the programmer pack at the very top of the list, or just above the modern resource pack, same result. Optifine stitches its textures back in, but then it hangs. I'll pastebin the next crash I get for a full output.

**Comment by lostkangaroo** [comment]
I can confirm the same issue and results as @capSAR273

Removal of the Ars-Nouveau allowed for resource packs to work.

**Comment by baileyholl** [comment]
Likely fixed here: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3143328

**Comment by Sunekaer** [comment]
Thanks @baileyholl !

**Comment by kd0pls** [comment]
The new version of Ars fixed it for me.  Thanks all!!
