### ISSUE TITLE
Direwolf20 1.16 crash issue regarding void ore miners in void dimension

### ISSUE THREAD

**Issue by charleycharley** [FTBTeam/FTB-Presents-Direwolf20-1.16#51]
Modpack Version:1.16

Issue:assembling a void ore miner in the void dimension corrupts the chunk and causes the game to crash and crashes the server. this happens every time the chunk is loaded

Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/f146c672

Is it Repeatable?: Yes

Mod/s Affected: environmental tech + Just Another Void Dimension

Known fixes: none

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by Sunekaer** [comment]
Please use https://paste.feed-the-beast.com/ for the crash log

**Comment by Sunekaer** [comment]
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/238
