### ISSUE TITLE
Can't pulverize fluix crystal in pulverizor

### ISSUE THREAD

**Issue by Pants44** [FTBTeam/FTB-Presents-Direwolf20-1.16#52]
* **Modpack Version**: 1.2.0

* **Issue**: Cannot pulverize fluix crystals in the Thermal Series Pulverizor anymore after update

* **Is it Repeatable?**: yup

* **Mod/s Affected**: Thermal Series & Applied Energistics 2

**Comment by Pants44** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4897#issue-776011283

**Comment by MacChuck** [comment]
You couldn't pulverize Certus in the thermal machines until a recipe was added, maybe this is similar? (patch notes for 1.2 of the pack include "Added Thermal and Immersive Engineering crushing recipes for Certus dust")

**Comment by Pants44** [comment]
> 
> 
> You couldn't pulverize Certus in the thermal machines until a recipe was added, maybe this is similar? (patch notes for 1.2 of the pack include "Added Thermal and Immersive Engineering crushing recipes for Certus dust")

I upgraded my server to the latest version today and had flux dust in my inventory that came from the thermal series pulverizor. Looks like the mod changed from Thermal Foundation to Thermal Series. Perhaps the recipe changes need to be done again.
