### ISSUE TITLE
performant cutting hostile mob spawns to almost nothing.

### ISSUE THREAD

**Issue by willrun4fun** [FTBTeam/FTB-Presents-Direwolf20-1.16#53]
Since the update of the pack this morning I was getting almost no hostile mobs.  I did some roll back of added stuff and performant was doing it.  Seems like others are also reporting the issue.

* **Modpack Version**: 1.2.0

* **Issue**: performant cutting hostile mob spawns to almost nothing.
* **Link to Log or Crash File Paste**: no crash from the issue

* **Is it Repeatable?**: yes.  played for two hours like almost on peaceful mode even though set to hard.

* **Mod/s Affected**: < fixed by removing performant.  After deleting the mod and relaunching spawns were back to normal.

* **Known Fix**: https://github.com/someaddons/performant_issues/issues/65

**Comment by Sunekaer** [comment]
Very weird, they spawned fine in my test world, but thanks for the report!

**Comment by robertm1771** [comment]
Am seeing spawns could be less then before 1.2.0 update but its a subjective test.

**Comment by willrun4fun** [comment]
For me is was drastic.  After removing it the night was thick with mobs again.  With it on I could go for a nice late night stroll in dark areas.  Just a thing to keep an eye on.

**Comment by e30Birdy** [comment]
I removed performant and my vanilla enderman spawner works fine again. Before I was literally getting no spawns nor were they wanting to attack my endermite.

**Comment by byrnejos000** [comment]
I am running DW20 1.16 version 1.2.0 and my mob farm has zero mobs coming out of it.

**Comment by Poke5555** [comment]
i too am having this problem, altho even after removing performant i still have drastically reduced spawns.

**Comment by Mopar** [comment]
I also *WAS* having this issue. I updated performant to the latest release and it *seemed* to resolve this issue. Before, I could take a casual walk through the nether for at least 15 mins, in the open, before coming across any mobs. Now the spawns *seem* normal, but further testing recommended.

**Comment by Sunekaer** [comment]
Thanks for the update Mopar
