### ISSUE TITLE
Server update changing chisel and bits block types

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Presents-Direwolf20-1.16#54]
* **Modpack Version**: 1.1.1 and 1.2.0

* **Issue**: Updating the server from 1.0 to 1.1.1, and from 1.1.1 to 1.2 caused stairs made with chisel and bits to change block types. Once from sediment stone from ExtCaves to an unknown block, and from 1.1.1 to 1.2 changed archwood planks to glass.
* Update was done on a linux server by deleting the following directories and running the newest installer: config, defaultconfigs, kubejs, libraries, local, logs, mods. (to keep whitelist, server properties, and world).

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Seems to be, I haven't installed every update, but both times I've updated the server this has happened.

* **Mod/s Affected**: Probably chisel and bits

**Comment by Sunekaer** [comment]
hmm thats every weird, havent seen that happen before.
Ill have to do some testing and asking around

**Comment by MacChuck** [comment]
Updating the server from 1.2.0 to 1.3.1 did the same thing. It converted the glass stairs (that we left in place from the 1.2 change) to a red and orange block with no localized name. Unfortunately I didn't see what the exact block was before that person tore it down and replaced with stone.

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
