### ISSUE TITLE
Mek Windgens don't work in Mining Dimension

### ISSUE THREAD

**Issue by OneLemonyBoi** [FTBTeam/FTB-Presents-Direwolf20-1.16#56]
* **Modpack Version**: 1.2.0

* **Issue**: Mekanism Wind gens don't work in Mining Dimension.

* **Is it Repeatable?**: Yes, moved it to 5 different locations and didn't work.

Looks like a Mek/JAMD interaction issue but not sure.

**Comment by MacChuck** [comment]
Has been an issue all along. The clock in the mining dimension spins like the nether, solar's don't work either. I just assumed the dimension is based on the nether format and has no functional wind/sun.

**Comment by willrun4fun** [comment]
yeah, things like wind and solar are commonly disabled in these dimensions to eliminate them being used for that.

**Comment by Sunekaer** [comment]
this is not a bug, thats how its meant to work
