### ISSUE TITLE
Direwolf20 1.16 v1.2.0 Traders and Plague doctors stuck invisible in day with drinking milk sound.

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Presents-Direwolf20-1.16#57]
* **Modpack Version**: 1.2.0

* **Issue**: Mobs that use invisibility at night will be stuck using milk and will not become visible in day

* **Link to Log or Crash File Paste**: 
 
* **Is it Repeatable?**: It's started with new update. Each morning if rat plague doctor or is traveling merchant. Is spawned near player. Mob will be stuck invis with buck of milk in hand making drinking noise.
 
* **Mod/s Affected**: Unsure assume new mob control AI added by Performant

* **Known Fix**: fastCollisions = true seems to cause the problem based on  https://github.com/someaddons/performant_issues/issues/61

**Comment by SRLcore** [comment]
I can confirm this issue. Disabling performant entirely resolves it for me.

**Comment by DreiPixel** [comment]
update perfomant to 3.26m fixes it.
