### ISSUE TITLE
Hard crash when putting Mekanism basic tank in Thermal's Tinkers' Workbench

### ISSUE THREAD

**Issue by zlepper** [FTBTeam/FTB-Presents-Direwolf20-1.16#58]
* **Modpack Version**: 1.2.0

* **Issue**: Game crashes when putting a mekanism basic tank in the Thermal Series Tinkers' Workbench

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b40d494c

* **Is it Repeatable?**: Yes, can't even open my world anymore :(

* **Mod/s Affected**: Mekanism and Thermal Series

I would report it to Thermal, however i cannot find their bugtracker, so for now this will have to do, since i assume you pass the reports along :)

**Comment by Sunekaer** [comment]
What fluid did you use?
I cant recreate this issue.
Also their current repo is https://github.com/KingLemming/1.16/issues

**Comment by zlepper** [comment]
I had a full tank of water. 

I don't recall if i had the watering can in the workbench also, but might have had. Based on the stack trace it looks like it's trying to extract fluid, so that might be required also.

**Comment by Sunekaer** [comment]
Thanks for the update

**Comment by Sunekaer** [comment]
you can back in to the world by open mc, go to singleplayer select the world click edit, click open world folder go in to serverconfig open forge-server.toml with a notepad change removeErroringTileEntities from false to true, save and load the world

**Comment by zlepper** [comment]
I managed to recover the world by using a world edit tool, so no biggie :) 
I have also passed the issue along to KingLemming.
