### ISSUE TITLE
Villagers not accepting POIs

### ISSUE THREAD

**Issue by Gloval** [FTBTeam/FTB-Presents-Direwolf20-1.16#60]
* **Modpack Version**: 1.2.0

* **Issue**: Have to place POIs down 20-30 times before a villager will claim it.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes, consistently

* **Mod/s Affected**: Vanilla Villager trades

**Comment by Gloval** [comment]
Also of note, unsure if related, when they finally do accept the POI the profession garb flashes onto the Villager, then off for a tic or 2 before fully taking.  Something appears to be intercepting the change.
I have, on someone elses suggestion, tried removing performant to see if it was causing the issue, it was not.

**Comment by Sunekaer** [comment]
POI?

**Comment by Gloval** [comment]
Point of Interest.
Lectern, crate, composter, Smithing Table, etc..

Playing with it further I have found that sometimes, if you put a POI down and leave it with the villager it will eventually claim it.  Can take a while, longest I noticed was about 10 minutes.

I've verified it is not a "Work hours" issue and not an issue of another nearby villager claiming the POI before the one I am working with.

**Comment by robertm1771** [comment]
I would bet that performant is the cause of this as it changes almost all AI. I would try disabling this to see if it resolves the issue

**Comment by Gloval** [comment]
As stated, already removed performant on someone else's suggestion, no change.

**Comment by Sunekaer** [comment]
hmm worked instantly in my test world, but I also have a newer version of some mods.

**Comment by Gloval** [comment]
Think I'm going to try removing ars and thermal to see if the villagers work properly. Both effect villager trading tables, maybe one of them is causing the issue or both trying to step in at once is the issue.

**Comment by Sunekaer** [comment]
Let me know what you find, are you playing in SP?

**Comment by Gloval** [comment]
Well, for some reason my instance won't load now, with not without the mods removed. Was playing SP. Not up for reinstalling the pack again right now, too frustrated.

**Comment by Gloval** [comment]
OK, so, if I remove Ars the issue clears in a new save.  In my existing save Villagers still take minutes to claim a POI.
Not sure I'm up for starting a 3rd new game for this pack right now.

**Comment by Sunekaer** [comment]
Could you check if you have the issue in version 1.3.1?

**Comment by Gloval** [comment]
As noted by a number of people 1.3.1 will not even load up, crashes shortly after the Initial forge load. I've since deleted the pack, may try again in a few months once the pack is more stable. My last testing was that with all intended mods loaded, in 1.2.1 I think, villagers work correctly at pack start and continue to until a bit of tech infrastructure is built. With a dynamo, pulverizer and redstone furnace they still seem to work but a few machines later and they start their waiting game. For now this can be closed.
