### ISSUE TITLE
Can't apply Particle Customizer (None) to Simply Jetpack

### ISSUE THREAD

**Issue by Shadowfire86** [FTBTeam/FTB-Presents-Direwolf20-1.16#63]
* **Modpack Version**: 1.2

* **Issue**: I have tried everything I can think of to apply the customizer to my Mekanism branched Ultimate Armored Jetpack, but it won't apply.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Simply Jetpacks 2

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Dev says the particles still are on the todo list, so they are not working yet.
