### ISSUE TITLE
[1.16.4] Ratlantis Dimension not working in pack v1.2.0

### ISSUE THREAD

**Issue by MacAttack-UK** [FTBTeam/FTB-Presents-Direwolf20-1.16#64]
* **Modpack Version**: 1.2.0

* **Issue**: Ratlantis Dimension not working but works in 1.1.2

* **Is it Repeatable?**: Yes, create a new SP world and R/Click a 'Chunky Cheese Token' on the floor

When you enter the portal you just get teleported back to the Overworld. With version 1.1.2 of the pack you get teleported to Ratlantis as intended.

**Comment by Sunekaer** [comment]
log?
Works fine for me in my test world

**Comment by DreiPixel** [comment]
Broke on my server too.

got into a loop where it tried to spawn me in ratlantis but spawned inside the portal in the overworld so it repeats.

log is only getting filled with

`[14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ma.commands.SpellPartArgument@70319828 (class com.ma.commands.SpellPartArgument) - will not be sent to client!
[14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@336c9b51 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@3d88bcd2 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@3affb07e (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
`

but that error happens even when someone joins so it is unrelated.

**Comment by Sunekaer** [comment]
> Broke on my server too.
> 
> got into a loop where it tried to spawn me in ratlantis but spawned inside the portal in the overworld so it repeats.
> 
> log is only getting filled with
> 
> `[14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ma.commands.SpellPartArgument@70319828 (class com.ma.commands.SpellPartArgument) - will not be sent to client! [14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@336c9b51 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client! [14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@3d88bcd2 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client! [14:58:40] [Netty Epoll Server IO #7/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@3affb07e (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client! `
> 
> but that error happens even when someone joins so it is unrelated.
> 
> edit: yeah even checked the debug log. only this error is happening. nothing else

that error isn't related to this

**Comment by MacAttack-UK** [comment]
Hi yeah my bad got distracted.

OK so I've just deleted logs created a new world, gave myself a token and created the portal. When I entered the portal I got the achievements etc. but then got teleported into the overworld high in the sky not far away and died from the fall.

Latest.log: [latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5759278/latest.log)

I should add that this is a fresh install of v1.2.0 as of yesterday and when I created the world I enabled cheats.

On my test server which has other mods/configs it crashes the server after spamming the logs as @DreiPixel posted. I didn't want to use the logs from that or mention it before as it's not a vanilla version of the pack. I've not has chance to build another test server yet to grab the logs from that.

**Comment by MacAttack-UK** [comment]
OK so I've just built a fresh new v1.2.0 server and joined that from the fresh client, created the portal and got teleported to the overworld after getting the achievements.

Server Logs:
[debug.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5759313/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5759314/latest.log)

Client logs:
[debug.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5759315/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5759316/latest.log)

**Comment by Sunekaer** [comment]
Please use paste.feed-the-beast.com for logs, so i don't have to download 100's of files and it easier to keep track off

**Comment by SmallSansSerif** [comment]
https://pastebin.com/K10wqWqr

Player going to Ratlantis for the first time crashed server, by running out of memory while this spammed in the console. After deleting that dimension folder player tried again and same result.

**Comment by MacAttack-UK** [comment]
OK so I looked at this issue #76 and disabled **performant-1.16.2-4-3.25m** and sure enough I was able to enter Ratlantis. I also tried replacing the current version with **performant-1.16.2-4-3.26m** which was released 4 days ago but then couldn't access Ratlantis again.

So to clarify, disabling the **Performant** mod I was able to enter Ratlantis on my vanilla pack test environment both when connecting to a server and in SP. I also tested this in my edited pack test server and was also able to enter Ratlantis in that world too.

Hopefully this will help narrow things down a little.tm :)

**Comment by Sunekaer** [comment]
Which is every weird Mac as i can enter the dim with performant

**Comment by Sunekaer** [comment]
Okay finally got it to happen for me after 13 tries.

**Comment by Sunekaer** [comment]
https://github.com/someaddons/performant_issues/issues/78

**Comment by xZILFx** [comment]
can confirm same thing is happening on our server. from what i can tell once you load into Ratlantis you get set right back to overworld. the process repeats over and over until the server crashes. the teleporting between detentions happens so quick you cant move. so once you step on the Ratlantis portal you are locked in a loop until you force close your game or the server crashes

**Comment by gorf18** [comment]
I have updated my server to use performant: performant-1.16.2-4-3.29m.jar . Can confirm Ratlantis is now accessible.
