### ISSUE TITLE
Terra Shatterer breaking bedrock.

### ISSUE THREAD

**Issue by JustLiam040** [FTBTeam/FTB-Presents-Direwolf20-1.16#66]
Modpack: Direwolf 20 1.16.4
Modpack version: 1.1.2

Essentially if you put a terra shatterer in awakened mode and break adjacent blocks it will in turn break the bedrock. This isn't exactly a useful bug but is definitely not ideal. Ive attached a video showing the bug. It should be noted that it is the same in a standalone Botania instance so it is most likely a Botania bug but have submitted it here to just make the devs aware.

https://user-images.githubusercontent.com/33065753/103424924-09bdfe00-4ba7-11eb-8df5-d8fc62a8ccc9.mp4

**Comment by Sunekaer** [comment]
Please test with version 1.2.0 of the pack as it has a updated version of Tetra

**Comment by Shadowfire86** [comment]
*Note to Sunekaer* Terra Shatterer is Botania item not Tetra.

**Comment by Sunekaer** [comment]
lol thanks xD idk what i was think when I looked at this issue

**Comment by Sunekaer** [comment]
https://github.com/Vazkii/Botania/issues/3583

**Comment by Lurae** [comment]
Confirming this issue still exists within latest update to the modpack 1.4.0

**Comment by SonicSpeedster16** [comment]
This should be fixed in the most recent version of the pack.

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
