### ISSUE TITLE
Got kicked out of the ME terminals when ordering the speed upgrade from AE2

### ISSUE THREAD

**Issue by LordGwinga** [FTBTeam/FTB-Presents-Direwolf20-1.16#67]
* **Modpack Version**: 1.2.0

* **Issue**: While ordering the speed upgrade from AE2 from any AE2 terminal i get kicked out of the terminal. edit: just tried making dense smart cable and it made my world save crash the game.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3b79624b edit: log for crash https://paste.feed-the-beast.com/view/c14d11c2

* **Is it Repeatable?**: Happened everytime i tried to order the item but did not affect other items.

* **Mod/s Affected**: Applied energistics 2

**Comment by IsaacWorkman** [comment]
I believe this is related to this thread on the AE2 github: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4893

**Comment by LordGwinga** [comment]
> I believe this is related to this thread on the AE2 github: [AppliedEnergistics/Applied-Energistics-2#4893](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4893)
> 
> Temporary workaround is to remake patterns to no longer accept substitutions.

I'll give it a try rn, thanks 👍

**Comment by shartte** [comment]
We just released appliedenergistics2-8.2.0-beta.2.jar, which should fix this (and another controller/energy-grid related crash)

**Comment by Sunekaer** [comment]
Thanks for the update @shartte

**Comment by Meowing-Cat** [comment]
Please push an update for this. :D thanks in advance!
