### ISSUE TITLE
Version 1.2.0 Sawdust Flooring recipe conflict.

### ISSUE THREAD

**Issue by bubbafett5611** [FTBTeam/FTB-Presents-Direwolf20-1.16#69]
Recipe conflict between thermal series Block of Sawdust and Immersive Engineering Sawdust Flooring
![sawdust flooring](https://user-images.githubusercontent.com/73138462/103435719-eadc5d80-4be0-11eb-97a6-3b64dd4a6298.png)
![Sawdust Block](https://user-images.githubusercontent.com/73138462/103435720-eb74f400-4be0-11eb-9c56-2dc2488f2058.png)

**Comment by Sunekaer** [comment]
Thanks for the report ill change the recipe to 
![image](https://user-images.githubusercontent.com/18720460/103442008-91ad1200-4c52-11eb-9bd4-00c61f54db67.png)
