### ISSUE TITLE
Create recipe issues

### ISSUE THREAD

**Issue by weightmaker** [FTBTeam/FTB-Presents-Direwolf20-1.16#71]
Pack Version: 1.2.0

trying to stick to the mod "Create" for ore processing but crushing wheel recipe is looping. 

- Crushing wheel needs brass ingot
- Brass ingot JEI recipe is not showing blaze cake but does not work. You need to use the blaze cake for it to work
- Blaze cake needs blaze cake Base
- Blaze cake base needs cinder flour
- Cinder flour needs Crushing wheel

**Comment by MacChuck** [comment]
You don't need blaze cake for brass. You need to heat the crucible under the mixer. You can put a blaze burner under it (with a captured blaze) and feed it any furnace fuel to heat it up.

**Comment by Sunekaer** [comment]
Only need the blaze cake for high/Super-Heated temp, for heated the Blaze Burner is enough
