### ISSUE TITLE
Comforts mod hammock not setting time to evening

### ISSUE THREAD

**Issue by Johnyxiade** [FTBTeam/FTB-Presents-Direwolf20-1.16#72]
When sleeping in the hammock, the day is fast forwarded by 1 instead of the time being set to evening on the same day.

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by DreiPixel** [comment]
Already reported it to the mod dev.
fixed in the next version.

https://github.com/TheIllusiveC4/Comforts/issues/50

**Comment by Firenzeo** [comment]
Since the other thread pertaining to this was identified as a conflict by the author, I took it upon myself to let Quetzi know.
https://github.com/Quetzi/Morpheus/issues/94
