### ISSUE TITLE
AE2 Crash loop. Repeatable.

### ISSUE THREAD

**Issue by Meowing-Cat** [FTBTeam/FTB-Presents-Direwolf20-1.16#73]
* **Modpack Version**: 1.2.0

* **Issue**: Crafting with Substitute Inputs in ae2 sends a server into a crash loop. AE2 have found the problem but cannot say when a fix will be out. but said people can roll back the current version

* **Link to Log or Crash File Paste**: https://pastebin.com/9XtCKNey

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Ae2

* **Known Fix**:  Downgrade to Alpha 2 supposely.

**Comment by Meowing-Cat** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/4899

**Comment by DreiPixel** [comment]
already reported. its the same as this: https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/67
