### ISSUE TITLE
Simply Backpacks Common Backpack stuck in AE2 system

### ISSUE THREAD

**Issue by torndar** [FTBTeam/FTB-Presents-Direwolf20-1.16#74]
* **Modpack Version**: 1.2.0

* **Issue**: I crafted a Simply Backpacks Common Backpack and put it in an AE2 system and I can't pull it back out.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: I'd expect so, can cheat another Applied Energistics system in to test if needed.

* **Mod/s Affected**: Applied Energistics 8.2.0-beta.1 and Simply Backpacks 1.16.3-1.4.13

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Im not able to recreate this issue.
Ill need more info about the system and the items in the  back and such

**Comment by torndar** [comment]
I stopped and restarted the server and I can pull it out now. I restarted the client before but not the server.

**Comment by Kvanr23** [comment]
I just had the same issue.
By pulling the storage cell out and putting it back, I was able to grab it from the system.
That saves restarting the server at least.
