### ISSUE TITLE
Game crashes due to ticking player

### ISSUE THREAD

**Issue by boiiking12** [FTBTeam/FTB-Presents-Direwolf20-1.16#75]
Sometimes when I am playing the pack the game will just freeze and the crash, when I look in the crash report it says it is due to a ticking player. I asked in the FTB discord and they told me to come here. I am not doing anything specific when I crash, like I am not opening a chest whenever I crash.
[crash-2021-01-02_11.08.38-server.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5760570/crash-2021-01-02_11.08.38-server.txt)

**Comment by Sunekaer** [comment]
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed.
Also please use Paste.Feed-the-beast.com for logs
