### ISSUE TITLE
Ratlantis crashes server and single player world

### ISSUE THREAD

**Issue by Pants44** [FTBTeam/FTB-Presents-Direwolf20-1.16#76]
* **Modpack Version**: 1.2.0

* **Issue**: trying to enter ratlantis crashes the game.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/57e9c190

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Ratlantis

**Comment by quietust** [comment]
I'm running pack version 1.2.0 with the Performant mod removed, and I was able to enter Ratlantis just fine (though it placed me inside solid rock so I had to dig my way out to stop suffocating).

**Comment by Sunekaer** [comment]
duplicate of #64
