### ISSUE TITLE
[1.2.0] Thermal jetpack crafting recipes missing

### ISSUE THREAD

**Issue by bubbafett5611** [FTBTeam/FTB-Presents-Direwolf20-1.16#77]
* **Modpack Version**: 1.2.0

* **Issue**: Thermal jetpack crafting recipes are missing

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Simply Jetpacks 2, Thermal Series

* **Known Fix**: n/a

**Comment by SonicSpeedster16** [comment]
Confirmed. Just came here to report the same thing. Pack version 1.2.0 also.

**Comment by Sunekaer** [comment]
https://github.com/Tomson124/SimplyJetpacks2/issues/26

**Comment by Th0mas-7** [comment]
Still waiting on Thermal to add some more items to make the recipes work, just popped them in there for people to see what is coming :D
