### ISSUE TITLE
Recipe Issue with Negative Chisel Design and Floppy Disk

### ISSUE THREAD

**Issue by dylantompkins** [FTBTeam/FTB-Presents-Direwolf20-1.16#78]
* **Modpack Version**: 1.2.0

* **Issue**: Unable to craft Chisels and Bits Negative Chisel Design. The recipe stated in JEI gives me a ComputerCraft: Tweaked Floppy Disk. Making this even more unusual, the recipe in question is not listed under Floppy Disk in JEI (the white Floppy is the only one that has recipes associated with it.)

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: The behavior shown in the attached screenshot always occurs, in both Refined Storage Crafting Grid and Vanilla Crafting Table.

* **Mod/s Affected**: `Chisels & bits Version: NONE` (Screenshot below) `CC:Tweaked Version: 1.95.0`

* **Known Fix**: No known fix

![image](https://user-images.githubusercontent.com/36244177/103494787-489dbf00-4e06-11eb-9e7d-698fba138eb6.png)
![image](https://user-images.githubusercontent.com/36244177/103494799-55baae00-4e06-11eb-99fb-aa762cf57f5c.png)
![image](https://user-images.githubusercontent.com/36244177/103494811-6408ca00-4e06-11eb-9e19-8d63bd8722ef.png)
![image](https://user-images.githubusercontent.com/36244177/103494822-6b2fd800-4e06-11eb-92c1-0ba5838c0ae2.png)
![image](https://user-images.githubusercontent.com/36244177/103494829-7125b900-4e06-11eb-9acd-a0eb1a687428.png)
![image](https://user-images.githubusercontent.com/36244177/103494834-76830380-4e06-11eb-9c0c-9949ccbbdf39.png)
![image](https://user-images.githubusercontent.com/36244177/103494838-7c78e480-4e06-11eb-9825-b7b53f6edf08.png)
![image](https://user-images.githubusercontent.com/36244177/103494896-b5b15480-4e06-11eb-87b1-9b6dda3d734e.png)

**Comment by Sunekaer** [comment]
Due to issue with CC-Tweaked - https://github.com/SquidDev-CC/CC-Tweaked/issues/652

**Comment by SquidDev** [comment]
Should be fixed in CC:T 1.95.1.
