### ISSUE TITLE
Version 1.20 : No AE2 meteroites in the world 

### ISSUE THREAD

**Issue by DietmarKrause** [FTBTeam/FTB-Presents-Direwolf20-1.16#79]
I have just started a new world in a fresh installation of DW20 1.16 Vers 1.20 and tried to find the AE2 meterorites. The compass is just spinning in circles and does not show a direction even after some exploration. Do i miss something ? Are the meteorites deactivated?

**Comment by DietmarKrause** [comment]
perhaps related: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4870 
is it possible, that the spawn of meteorites is deactivted out of that reason (see link)  so we have to cheat the missing items in ?

**Comment by Sunekaer** [comment]
We dont use world bender, so that link isnt relevant.
Ill have to check this later when I'm not a work.

**Comment by Sunekaer** [comment]
try and run this command: `/locate appliedenergistics2:meteorite` it will find the closed one that it can find
Like this
![image](https://user-images.githubusercontent.com/18720460/103569111-04262800-4ec7-11eb-9bc4-898cc00eb911.png)

**Comment by DietmarKrause** [comment]
that command gives this result: 
![image](https://user-images.githubusercontent.com/4482657/103577456-2757d400-4ed5-11eb-968a-f0eef02e20a3.png)

**Comment by SonicSpeedster16** [comment]
I started a fresh world on a server using version 1.2.0 and my players have found a number of meteorites.

**Comment by DietmarKrause** [comment]
does this mean: the compass is not working ?

**Comment by DietmarKrause** [comment]
![image](https://user-images.githubusercontent.com/4482657/103578025-270c0880-4ed6-11eb-95c9-0a66da767a70.png)
 
compass shows the meteorite only if you are very near to it.

**Comment by DietmarKrause** [comment]
after i mined every sky stone the compass keeps pointing to that location. Is there any way to find additional Meteorites ?
