### ISSUE TITLE
Game refuses to launch, and crashes before a full error report is generated.

### ISSUE THREAD

**Issue by rtr468** [FTBTeam/FTB-Presents-Direwolf20-1.16#8]
V1.0.0

Modpack refuses to launch, have re-installed and it still refuses to launch. 

https://paste.feed-the-beast.com/view/41be84a9

It is repeatable, even through re-install

**Comment by capSAR273** [comment]
I would post a full log if you can just so all info is available.

**Comment by rtr468** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5713298/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5713300/latest.log)

Is this what you meant? I apologize for not having it readily available

**Comment by Sunekaer** [comment]
Please use https://paste.feed-the-beast.com/ for the logs

**Comment by rtr468** [comment]
https://paste.feed-the-beast.com/view/70752975 for debug.log
https://paste.feed-the-beast.com/view/01058c8c for latest.log

**Comment by Sunekaer** [comment]
Could you try and delete this folder and its files C:\Users\Richie\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.16.4-35.1.13
And then reinstall the pack

**Comment by rtr468** [comment]
I have done as you intructed, however it did the same thing. 
https://paste.feed-the-beast.com/view/085fc4b5 for debug.log
https://paste.feed-the-beast.com/view/d3ce85b2 for latest.log
is there anymore I need to do past deleting that and reinstalling?

**Comment by rtr468** [comment]
only one of those existed, there was a forge 1.12 there too, so I deleted that one as well, expecting to install that one again later on. It has begun loading now.

**Comment by rtr468** [comment]
it has loaded succsessfully

**Comment by Sunekaer** [comment]
Thats great to hear!
Let use know if you have other issues
