### ISSUE TITLE
AE2 autocrafting caused my multiplayer server to crash infinitely

### ISSUE THREAD

**Issue by mayday014** [FTBTeam/FTB-Presents-Direwolf20-1.16#80]
https://pastebin.com/gLAZBQFd

* **Modpack Version**: <1.2.0 multiplayer server

* **Issue**: There is a bug I think with applied energistics that has caused an infinite loop, causing my multiplayer server to crash constantly. I tried to autocraft molecular assemblers I think for the first time and the server crashed and wouldn't restart. Only thing I could do was load a backup. There were 3 people on at the time, but I'm pretty sure this is the cause since it crashed as soon as I confirmed the autocraft.

* **Link to Log or Crash File Paste**: https://pastebin.com/gLAZBQFd

* **Is it Repeatable?**: Haven't tried

* **Mod/s Affected**: AE2 (I think)

* **Known Fix**: had to roll a backup :(

**Comment by Sunekaer** [comment]
Could you try and change eventLoadBalancing to false in performant-common.toml in the config folder and see if that fixes the issue

**Comment by Sunekaer** [comment]
Could you try remove performant from server and test?

**Comment by mayday014** [comment]
I haven't tried from that specific world file again yet, but I am still running into problems after I rolled back the server and continued playing. Any decently big autocrafts are throwing errors. For instance, I can autocraft a 4k crafting storage, but if I try to go up to a 16k crafting storage, it throws an error. Same with any mekanism jetpacks that I've tried. I have not tried removing performant yet, that is what I'm going to do now on the original server problem.

https://paste.feed-the-beast.com/view/723c1c3b

**Comment by mayday014** [comment]
Here is the crash log after removing performant from the server files.
https://paste.feed-the-beast.com/view/84c700ba

**Comment by mayday014** [comment]
?

**Comment by mayday014** [comment]
Server crashed again, this time while trying to make basic universal cables.

https://paste.feed-the-beast.com/view/a4f8704d

**Comment by IsaacWorkman** [comment]
Can I suggest replacing all your AE2 autocrafting recipes with versions that don't accept ore dictionaried items? Looking at your crash logs, this appears related to this bug: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4893

This looks to be fixed in newer / dev versions of AE2, but not for the 1.2 version of the pack. The above suggestion has halted crashes in my experience, until a fixed version is pushed to the pack.

**Comment by mayday014** [comment]
Putting the newest version of the mod into the server fixed the hard crash. Thanks for the help!
