### ISSUE TITLE
Tetra mod workbench non-functional

### ISSUE THREAD

**Issue by NixxNikoli** [FTBTeam/FTB-Presents-Direwolf20-1.16#83]
* **Modpack Version**: 1.2.0

* **Issue**: Tetra Workbench has no UI or interactability. Tools in hand, empty handed or otherwise there is no way to access the UI. I have tried the mod keybinds in Controls but none of them seem relevant

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Repeatable after restarting client, destroying and recreating block (right-click a vanilla crafting bench with the mods hammer) and combinations thereof

* **Mod/s Affected**: Tetra 3.4.0

* **Known Fix**: ?

**Comment by NixxNikoli** [comment]
Potentially just a glitch. After a full computer restart the mod is functioning correctly now. Unknown what has changed

**Comment by SonicSpeedster16** [comment]
Unable to reproduce. I've been playing with Tetra workbench from basically the beginning of the pack and have not had any issues interacting with the workbench. Pack version 1.2.0
