### ISSUE TITLE
internal server locks up or stops sending terrain data while exploring certain chunks.

### ISSUE THREAD

**Issue by Dutchs** [FTBTeam/FTB-Presents-Direwolf20-1.16#84]
* **Modpack Version**: 1.2.0
* **Issue**: While exploring, a certain area first starts to load more slowly and ultimately stops loading new chunks.
Sometimes exiting the area will cause the internal server to recover but other times it locks up in which case it will get stuck when attempting to Save and Quit to Title and requires that you force kill the java process.
* **Is it Repeatable?**: Yes
Seed: 2520887626484957534
Pos: 700, -650

**Comment by n4imLess** [comment]
Same problem at: 
Seed:-5651870358209890114
Location where it starts to stop loading chunks: -1700 110 -3300 (north bound)
TP:/tp -1700 110 -3100

Note: We tested stuff and for us the chunks loaded when we removed/disabled Astral Sorcery. But it did work in a world with only AS. So it also might be something totally unrelated to AS and is indeed a AE/MaA issue.
We tried it on a local server and single player. Both hang/crash.

**Comment by Sunekaer** [comment]
from #105 AppliedEnergistics/Applied-Energistics-2#4891

**Comment by shartte** [comment]
The actual reason for the deadlock is that the chunk lighting threads crash with a null-pointer-exception. The code for chunk lighting is a byzantine mess, so not a ton I can do. It's possibly a combination of AE2 carving out a massive area of stone for the impact area where another mod previously placed light-emitting blocks??? (this is a wild guess).

See the linked issue for the stack trace in the chunk lighter. Affected chunks do also load with only AE2 installed.

**Comment by Sunekaer** [comment]
> * **Modpack Version**: 1.2.0
> * **Issue**: While exploring, a certain area first starts to load more slowly and ultimately stops loading new chunks.
>   Sometimes exiting the area will cause the internal server to recover but other times it locks up in which case it will get stuck when attempting to Save and Quit to Title and requires that you force kill the java process.
> * **Is it Repeatable?**: Yes
>   Seed: 2520887626484957534
>   Pos: 700, -650

@shartte 
Is this case its both AE and Mana and Artifice there is trying to place a structure in the same location that's the only thing I have found that it could be 
![image](https://user-images.githubusercontent.com/18720460/104220985-8f139f00-5440-11eb-87df-77a09e7ede79.png)
![image](https://user-images.githubusercontent.com/18720460/104220998-96d34380-5440-11eb-9952-ca653c3e5242.png)

If its not that then idk why it happens

**Comment by shartte** [comment]
So I was able to actually fix this by building a special build that places obsidian columns from y=0 to y=255 in each chunk that's touched by the meteorite generator.

Here's my working theory: When we completely clear a chunk-section (chunks are vertically partitioned into sections of 16 blocks), the lighting engine actually removes the backing lighting data. There seems to be a post-processing step for light-*emitting* blocks (i.e. lamps, like the ones I see on your screen) which assumes the chunk lighting data exists, leading to this crash. 

I have no idea if that's actually the problem, and no idea how to fix it though. Oops.

**Comment by shartte** [comment]
Okay, that was it. Vanilla light-update bug.

We're pushing a workaround for the Vanilla bug in beta3 (not yet released).

**Comment by Sunekaer** [comment]
Awesome! Thanks a lot @shartte !

**Comment by djanse** [comment]
I had similair a similair issue reported in #90 Since a new version (1.4.0) has been launched i decided to check up on these locations. The reported location does not seem to luck up the server anymore but another location we've found in our world still does. Chunks are barely send and closes the server after about 1-2 minutes.

Was the issue supposed to be fixed in this version or has it been scheduled for later release?

**Comment by shartte** [comment]
The fix was not yet released.

**Comment by shartte** [comment]
We've released 8.2.0-beta.3 with a bunch of fixes that should also fix this issue.

https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/v8.2.0-beta.3
