### ISSUE TITLE
Can't join papaermc vanilla server behind Waterfall proxy i use as hub on server network

### ISSUE THREAD

**Issue by Laikar** [FTBTeam/FTB-Presents-Direwolf20-1.16#85]
* **Modpack Version**: 1.2

* **Issue**: I have a minecraft server network behind a waterfall proxy, when a client connects it is placed by default on a papermc vanilla 1.16 server where they can change to any of the servers on the network, when joining with the direwolf20 1.16 pack i get a decoder exception on the client, and no error on both the server or the proxy.
 Also, i can connect to a regular direwolf20 1.16 modpack on the same machine as the proxy and the vanilla server
 I am using MultiMC as a launcher.

* **Link to Log or Crash File Paste**: https://paste.ee/p/xys8f.
On this log i tried joining the vanilla server, got the error, then joined the direwolf1.16 server succesfully, and the tried joining the vanilla server again

* **Is it Repeatable?**: yes, it allways happens

* **Mod/s Affected**: the errors are logged by malte0811.recipebuffers, but i don't really know if that is the cause

* **Known Fix**:

**Comment by Sunekaer** [comment]
Hi Laikar
As your running a bunch of software on top of the pack that we have no experience we won't be to much help here.
All I can recommend you is to make an issue with the mod author https://github.com/malte0811/RecipeBuffers 
Thanks
Sunekaer
