### ISSUE TITLE
Main menu image scaling shows artifacts > 1600 pixels wide

### ISSUE THREAD

**Issue by capSAR273** [FTBTeam/FTB-Presents-Direwolf20-1.16#9]
* **Modpack Version**: 1.0.0

* **Issue**: Images laid on top of the main menu background don't scale to high resolutions. Seems to only be visible on a resolution greater than 1920X1080, mine is 2560X1440.

* **Is it Repeatable?**: Yes, each launch

* **Known fix?**: Probably just need to scale up the images of Dire and the Pack name so they support higher resolutions. The issues is with the width of the window. At 1600x1440 the main menu shows up without any outlines or artifacts. Once its widened past that point, the lines will show up.

1600x1440: 
![image](https://user-images.githubusercontent.com/5252505/102559104-1289dc80-409d-11eb-890a-c202098f29e1.png)

1602x1440:
![image](https://user-images.githubusercontent.com/5252505/102559381-b6738800-409d-11eb-9fbd-c7139ec97589.png)

**Comment by capSAR273** [comment]
I'm going to test scaling up packname.png and person.png from the kubejs folder to see if I can get rid of the outlines.

**Comment by Sunekaer** [comment]
Could you try and replace the content of /kubejs/client_scripts/ui.js with the content from this link https://paste.sunekaer.com/aficecabut.js

**Comment by Sunekaer** [comment]
Let me know how it goes

**Comment by capSAR273** [comment]
Replaced with the .js you posted, looks like the line above Dire is gone, but the other 2 lines remain:
![artifacts](https://user-images.githubusercontent.com/5252505/102680636-0d558c00-4188-11eb-8201-6801e9ca55ee.png)

**Comment by Sunekaer** [comment]
Okay thanks, then ill do some tweaking to the pics and the code and hopefully, the last lines should be gone in the next update
