### ISSUE TITLE
Hard crash, using the workbench from Cyclic 

### ISSUE THREAD

**Issue by Jin16** [FTBTeam/FTB-Presents-Direwolf20-1.16#94]
* **Modpack Version**: <1.2.0>

* **Issue**: When clicking on Empty the grid button, minecraft crash to desktop 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/be6ddabd
https://youtu.be/dW6qdfmdQvQ
* **Is it Repeatable?**: YES 

* **Mod/s Affected**: Cyclic 

* **Known Fix**:

**Comment by n4imLess** [comment]
Fixed already in a newer version of Cyclic: https://github.com/Lothrazar/Cyclic/issues/1652
Wait for a update of the modpack or update cyclic :)
