### ISSUE TITLE
Version 1.3.0 Server files on Windows not working

### ISSUE THREAD

**Issue by BenOHedges** [FTBTeam/FTB-Presents-Direwolf20-1.16#97]
I downloaded the FTB Presents Direwolf20 1.16 - 1.13.0 Windows server files, moved it to my main server directory and tried to run it but it opens and closes a terminal, no changes / updates happen. 

Moved it to an new empty directory but nothing was created or made.

I cant easily get a reliable screenshot as it pops up and disappears in less than a second but here is what i was able to grab

![image](https://user-images.githubusercontent.com/74880181/104091568-15c85080-5276-11eb-870b-beab77fc5509.png)

**Comment by Sunekaer** [comment]
Full log of the install?

**Comment by Sunekaer** [comment]
Worked fine on my pc

**Comment by BenOHedges** [comment]
I did a few more tests after i posted this as i couldnt get the previous server update working, indicated It was a problem on my machine. My PC did a restart since the last time i ran the server and now i have to run the severinstall_79_217.exe file as admin to install. 

Currently trying to run the start.bat but it now opening and closing as well

**Comment by BenOHedges** [comment]
Got it working

Upgrading my previous server files from the previous version (1.2.0) of this pack wouldnt work. I created a new folder and started from scratch, had a few errors with the start.bat file, first crash was with xNet and after re launching the bat file again it overcame this. Copied the world folder over and its working now.
