### ISSUE TITLE
Missing Ores from Mekanism Processing

### ISSUE THREAD

**Issue by InsaneVirus** [FTBTeam/FTB-Presents-Direwolf20-1.16#98]
- Modpack Version:
1.2.0

- Issue:
The following ores are missing from Mechanism's triple/quad ore processing recipes:
Zinc Ore (Create)
Silver Ore (Thermal Series)
Nickel Ore (Thermal Series)
Bauxite Ore (Immersive Engineering)

- Is it Repeatable?:
Always

- Mod/s Affected:
Create
Mekanism
Thermal Series
Immersive Engineering

**Comment by Sunekaer** [comment]
This is due to that mekanism isnt adding them, we are not going  to add them ourself.
So this will only be changed if Create, IE and thermal add recipes for these
